### ISSUE TITLE
DDS Preview 'Pick background colour' broken

### ISSUE THREAD

**Issue by cibrhusk** [ModOrganizer2/modorganizer#1060]
## The problem:
When you Preview a texture that is partly transparent you get the checkered pattern. Sometimes you need to change the background color so you can review white textures that are partly transparent. There apparently exists a button to do this but setting a color does not change the color for the checkered pattern. Closing and reopening preview also has no effect.

## To Reproduce:
1. Install a mod with transparent textures (or create one from vanilla bsa sources in any game)
2. Open the information screen
3. Open the dds texture with preview, either from Filetree or from Conflicts
4. Press the button 'Pick background colour'
5. Choose a different color (black, green, whatever)
6. Press OK
7. see that background remains the same

## Environment:

* Mod Organizer Version that exhibits the issue: v2.2.2.1
* Desktop OS/version used to run Mod Organizer: Win 10 1909

**Comment by cibrhusk** [comment]
When rechecking the issue it was caused by the alpha channel setting, it was set to 0 causing the chosen color not to be visible.
I don't remember ever setting the alpha channel to 0 but its probably a logical default, unless someone wants to change the background color and looks only at the color picker ;-)
Perhaps a better default would be something that combines a higher alpha channel with a near white background color. 50 together with #1143 html #eeeeee for example. Or something that changes the alpha channel when using the color picker.

**Comment by AnyOldName3** [comment]
It kind of *is* a bug as the UX for the colour picker is terrible when an alpha channel is involved. It's just Qt's bug rather than ours. I'd hoped someone in the know would see the thread I made and agree, but that's not happened. Maybe if more people replied to the thread agreeing that something needed to change, it would bump it to the top of their list again (increasing the chance that someone important actually sees it) and make them treat it as a higher priority if they did.
