### ISSUE TITLE
Plugins frameworks like BepInEx not loading from VFS from Mods folder for 3dparty Unity games.

### ISSUE THREAD

**Issue by TokcDK** [ModOrganizer2/modorganizer#1164]
## The problem:
When for example for Unity game in Data folder with BepInEx framework files placed in Mods\Bepinex, enabled and game exe executed from MO then BepInEx will not be loaded and his cfg files will not be created even if his files appeared in VFS folder.

## To Reproduce:
1. Any Unity game demo\full placed in Data.
2. Configured or any base plugin with dummy exe placed near of Data or configured game plugin based on  [base game](https://github.com/holt59/modorganizer-basic_games) plugin.
3. [BepinEx archive](https://github.com/BepInEx/BepInEx/releases) extracted to mods\BePinEx\ folder. Also can be other plugin like [XUnity.Autotranslator](https://github.com/bbepis/XUnity.AutoTranslator/releases) placed to mods to see if it will be loaded or not.
4. All plugins enabled in MO and appeared in virtual folder structure like thy must be in real game folder.
6. Executed game exe and BepInEx is not loaded and it cfg file not appeared and plugin also not loaded.

Files Structure:
TestFolder\
TestFolder\Data\ - folder for VFS
TestFolder\Data\unitygame.exe
TestFolder\Data\unitygame_Data
TestFolder\MO
TestFolder\MO\mods\BepInEx - bepinex folder with files here BepInEx\winhttp.dll, BepInEx\doorstop_config.ini, BepInEx\BepInEx\core\...

VFS shows structure like this:
VFS\winhttp.dll
VFS\doorstop_config.ini
VFS\Bepinex\
VFS\unitygame.exe
VFS\unitygame_Data\

## Environment:

* Mod Organizer Version that exhibits the issue: +2.3RC2
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):-
* Desktop OS/version used to run Mod Organizer:W7

## Details:
Was also tried executableForcedLoads and added winhttp.dll preloader from Bepinex folder as library but no effect. Tried add extra dlls of Bepinex for force load list but also no effect.
On current moment only one workaround was found to load Bepinex it is to copy winhttp.dll, doorstop_config.ini and BepInEx\core\BepInEx_preloader.dll to Data folder and only after this actions Bepinex is loading but then other files except game files will be in game folder.

**Comment by Al12rs** [comment]
I assume that winhttp.dll is a windows dll that the game loads by default (load time dynamic library) and that the framework is placing in the game folder to override the default one and make that one load the other dlls in turn.

Usvfs has the limitation that it only starts rerouting things after it has initialized itself inside the game process. This is done by changing the main() entry point of the process to the usvfs init function and then returning to the main(). This has the disadvantage that Load Time dlls are loaded before main(), so any code executed in the DLLMain() of those dlls is not running under VFS. As windows guideline, you shouldn't actually do anything complex in DLLMain, especially loading other Dlls like what I think is happening here, but well some modding stuff do that.

There isn't much to do here I'm afraid. usvfs initialization is too complex to happen before other dlls are loaded. Usvfs itself relies on other libraries to be loaded before it.

What you can try is to load BepInEx_preloader.dll with force load library. 
Force loading the winhttp.dll will not work since the default windows one will already have been loaded at that point (when usvfs initializes and tries to load Force loaded dlls (they aren't really forced, just a normal LoadLybrary() is called with no real context of what is getting loaded though).

**Comment by TokcDK** [comment]
Tried to load and BepInEx_preloader.dll and BepInEx.dll. Also tried several other variants with force dll when some dll was added in Data and some was in Mods. Still no results and still working variant with adding all winhttp.dll, doorstop_config.ini and BepInEx\core\BepInEx_preloader.dll to Data folder, just to add winhttp.dll with doorstop_config.ini is not enough and even if after added winhttp.dll in Data and added Mods\BepinExModdir\BepInEx\core\BepInEx_preloader.dll to process forced library Bepinex will not be loaded and BepInEx\core\BepInEx_preloader.dll also must be added in Data with first two files.
Will try some other combinations.

**Comment by Al12rs** [comment]
I guess that BeplnEx.dll might also need to do stuff before main start, thus the preloader. In that case usvfs can't do much.
Basically if you don't have winhttp.dll in the game folder the original is loaded instead. If you do have it present but the BeplnEx.dlls are missing then the modified winhttp.dll will try to load them and not find them (since usvfs isn't active yet at the moment when winhttp.dll is loaded into the game).
So on and so forth. So it makes sense if it only works if you have all the files that are touched on loadtime in the actual data folder.

**Comment by TokcDK** [comment]
Maybe MO force library loading can make same things like BepInEx_preloader.dll for frameworks like BepInEx? [BepInEx](https://github.com/BepInEx/BepInEx) is open source project and [NeighTools/UnityDoorstop](https://github.com/BepInEx/BepInEx) winhttp preloader also open source.

**Comment by Al12rs** [comment]
I'm afraid that what Doorstop is doing is too complex for what the Force Load Library feature is capable of. It appears to me that they also need to do their work (preload) before other Load Time dlls are done loading. Usvfs on the other hand loads after all dlls are loaded and the process in unsuspended (as usvfs replaced main() with it's own initialization function). After the init is done usvfs tries to load in libraries. This sounds like way too late for your needs with BeplnEx.

**Comment by jarrard** [comment]
Maybe if force load had 1 more option to load pre-usvfs or not on DLL's. Perhaps that could work I dunno.

**Comment by Al12rs** [comment]
It would defeat the purpose of virtualizing those dlls. I'm closing this since it's a limitation of usvfs and there is nothing we know that can be done.

**Comment by TokcDK** [comment]
Bad if nothing can be done in current moment. Bepinex using with lot of games for modding purposes and all of them will be incompatible with MO because this "limitation" and because MO need only for modding. Tried MO with other games where was other loaders for mods and plugins and they also loading nothing when game working with MO.. Hope sometime someone will fix it in MO or on side of BepInEx...
