### ISSUE TITLE
Option to prevent moving modified files to overwrite folder?

### ISSUE THREAD

**Issue by fireundubh** [Modorganizer2/modorganizer#124]
Can an option to prevent modified files from being moved to the overwrite folder be added? I use junction points to Git repos as mod folders, so moving files I've edited is not desirable.

**Comment by oabdellatif** [comment]
The default behavior should definitely be to _copy_ any modified files to the overwrite folder, not move them. When I clean the official masters using SSEEdit, for example, they are moved outside of the data folder and then the game is be unable to launch except through MO.

**Comment by Silarn** [comment]
For unmanaged mods, I do think we should bypass redirection. It's also possible with mod files but it's going to require technical hurdles which would slow down the VFS. For a CreateFile, we would probably need to duplicate the file if the application asks for write permissions and open the new file instead. But there's no guarantee the file will actually be modified, and that approach would likely create a bunch of duplicated files even if they were not modified.

So do we then run a hash check on the files to see if they are identical and remove the new file in that case?

Do we hook file writes and then somehow reroute the write to a new file instead? How much slower would that make the operation?

**Comment by Silarn** [comment]
The original request is probably going to require an extension to USVFS and is thus going to take more time if we decide to go ahead with it. Currently USVFS either reroutes a directory/file or it doesn't. There's no 'maybe sometimes' involved. That being said, if a file is directly edited rather than recreated, it already works this way.

There are some limited options available to instruct USVFS how to handle certain mappings. We'll just need to investigate more.

**Comment by Al12rs** [comment]
This has usvfs has been changed to always edit the original file and not move it to overwrite in usvfs 0.31 beta 5 available on discord.
