### ISSUE TITLE
Clean Install of Skyrim SE, MO2, SKSE, and all Mods Won't Launch SKSE or Skyrim from MO2.

### ISSUE THREAD

**Issue by Zetawilk** [ModOrganizer2/modorganizer#1247]
After having conducted a completely fresh install of Steam, Skyrim SE, MO2, SKSE, then the few mods I'm using, MO2 is unable to launch either SKSE or Skyrim SE itself. Outside of MO2, SKSE launches Skyrim SE accordingly, albeit without mods.

**Comment by LostDragonist** [comment]
Does it work without "the few mods" you're using?  Mods can crash the game pretty easily if you do things wrong.  Without having a list of the mods (with lots of details), it's next to impossible for us to guess.

**Comment by Al12rs** [comment]
To check whether the issue is related to one of the mods installed or your ini settings, see if it keeps happening in a new empty profile:
https://cdn.discordapp.com/attachments/403979692501106688/524939782435110924/unknown.png
https://cdn.discordapp.com/attachments/403979692501106688/524940397643038740/unknown.png

**Comment by isanae** [comment]
Reopen if you have more information.
