### ISSUE TITLE
When Enabling All Visible Mods in left pane, place plugins in left pane in same order

### ISSUE THREAD

**Issue by coldrifting** [ModOrganizer2/modorganizer#1263]
When troubleshooting mods, I often like to disable all mods except the ones I am working on, and then later enable all mods. Enable All used to put all mods plugin files in the right pane in the same order as the left pane. Right now though, It places them in alphabetical order, which I can't see a reason for.

I would like for plugins to be added in the same order as the mods they are from, so that mod and plugin order is synced initially. If alphabetical sorting is still desired, perhaps it could be toggled by a checkbox in the settings dialogue.

**Comment by LostDragonist** [comment]
The reason this behavior changed is because the old way was slow af.  It would enable the first mod, do a complete refresh, enable the second mod, do a complete refresh, enable the third mod, do a complete refresh etc.  When dealing with hundreds to thousands of mods, this was not good.

Now, it enables all the mods at once and does a single complete refresh.  All the missing plugins are added alphabetically because that's just how they're sorted.  

This could be a good candidate for a tool plugin to "sync" the order of the plugin list according to the mod list.  That's not to say it couldn't be built into the main program, if someone wants to do it, but I don't think it's useful enough behavior to be required every time you enable multiple mods at once.

**Comment by coldrifting** [comment]
I've Created a plugin to do this here: https://www.nexusmods.com/skyrimspecialedition/mods/47325
