### ISSUE TITLE
Add support for game [Dark Souls]

### ISSUE THREAD

**Issue by dirknina** [ModOrganizer2/modorganizer#1273]
**This template is useful to add basic support using https://github.com/ModOrganizer2/modorganizer-basic_games.** 

**If you are vaguely familiar with programming you can try following the instructions on that link to get something working yourself. If you have trouble with that please fill in this template.**

**Please provide the following information for the game (remove the optional lines you do not use):**

- **Name:** Dark Souls
- **Short name:** Darksouls
- **Nexus ID [optional]:** https://www.nexusmods.com/darksouls
- **Executable:** DARKSOULS.exe
- **Data path:** Dark Souls Prepare to Die Edition\DATA
- **Documents path:** Dark Souls Prepare to Die Edition\DATA
- **Steam ID [optional]:** 211420
- **Saves path.** Documents\NBGI\DarkSouls
- **Saves File.**  .sl2

**Provide additional details regarding the game that could be required for the plugin.**

**Comment by Holt59** [comment]
You can try installing the latest version of https://github.com/ModOrganizer2/modorganizer-basic_games, it should detect Dark Souls.

Unfortunately, I don't really know if anything will work since I did not find a single plugin that I could simply put in the VFS. You'll likely have to install DSFix in the actual game directory (maybe the DLL will be sufficient, I don't know).

**Comment by dirknina** [comment]
DSFix has to go in main directory maunualy.  mods that replace textures  work but has to have folder path of DATA\dsfix\tex_override.   haven't tried it with any that adds content  but for textures mods to work it needs that pathing.  i appecate your hard work and quick makeup of pulgin

**Comment by Holt59** [comment]
Closing. Feel free to re-open or open specific issues if you encounter problems with the plugin or if you'd like new features.
