### ISSUE TITLE
SkyrimVR not loading when using SKSEVR

### ISSUE THREAD

**Issue by Tatts4Life** [ModOrganizer2/modorganizer#1318]
## The problem: 
SkyrimVR doesn't load when launching SKSEVR through MO2. The Steam loading screen pops up and just says waiting for game to load. When loading the game outside of MO2 the game starts right away

## To Reproduce:

1. install SKSEVR
2. click on run

## Environment:

* Mod Organizer Version that exhibits the issue: V2.3.2
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Windows 10

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your latest USVFS log, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by Al12rs** [comment]
To check whether the issue is related to one of the mods installed or your ini settings, see if it keeps happening in a new empty profile:
https://cdn.discordapp.com/attachments/403979692501106688/524939782435110924/unknown.png
https://cdn.discordapp.com/attachments/403979692501106688/524940397643038740/unknown.png

Also make sure you don't have any mods installed in actual game folder, and test if the issue happens outside of Mo2 if you didn't already.
