### ISSUE TITLE
Razer Cortex warning probably obsolete

### ISSUE THREAD

**Issue by Darklocq** [ModOrganizer2/modorganizer#1325]
## The problem:
MO2 throws up multiple warnings about Razer Cortex (specifically objecting to EasyHook64.dll and k_fps64.dll), and rather wrongheadedly advising "Consider uninstalling it."

## To Reproduce:

1. Install Razer Cortex
2. Install MO2.
3. Run MO2.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.3.2
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): No idea.  PS: "Verison" isn't a word. :-)
* Desktop OS/version used to run Mod Organizer: Windows 10 Enterprise v. 2004 (Build 19041.508)

## Details:
MO2's Log section reports "This program is known to cause issues with Mod Organizer, such as freezing or blank windows. Consider uninstalling it.", in reference to both Razer Cortex components. I've been running them together for months without any issues. It seems likely that whatever issue there once was has been resolved.  To the extent that Cortex or any other third-party FPS monitor and other "overlay" software might conflict with a game itself, that's an issue between the developers of that utility and the developers of that game, and has nothing to do with MO2 in the first place.  Maybe the implication was the Cortex was in fact interfering with MO2 itself, but that no longer seems to be the case.  I would think this warning should be removed, or should only be triggered in the presence of versions of Cortex known to cause such problems.

### USVFS:
[https://gist.github.com/Darklocq/2c870036bc23b8f2f7e8066641b2049f](https://gist.github.com/Darklocq/2c870036bc23b8f2f7e8066641b2049f)

### MO Interface:
[https://gist.github.com/Darklocq/5deb1ff68e895657df93d7ce9cde17e8](https://gist.github.com/Darklocq/5deb1ff68e895657df93d7ce9cde17e8)

**Comment by isanae** [comment]
The problems with overlays seem inconsistent. Some people have no problems with them, others report blank windows until they uninstall them. The last confirmed report of Cortex being a problem looks to be in April, but it's impossible to say if it's "probably obsolete" because the point of the warning is to give enough information to users so they can fix the problems themselves instead of coming on the Discord for help.

I have no intentions of trying to figure out which versions of which software causes problems. I can't even install most of this stuff because I don't have the hardware for it. The whole point of the warnings is to decrease our workload, not increase it.

In any case, I would need much better data than this to decide to remove the warning, so it'll stay for now.
