### ISSUE TITLE
Methods in python implementation of ISaveGame are not being called

### ISSUE THREAD

**Issue by erri120** [ModOrganizer2/modorganizer#1430]
## The problem:
The following functions are never being called by MO2:
- `getName`
- ~~`getSaveGroupIdentifier`~~
- ~~`allFiles`~~

See ModOrganizer2/modorganizer-basic_games#35 for a save game class that implements `getName`. Opening the saves tab in MO2 with that plugin will not call the implemented `getName` function.

**Comment by Holt59** [comment]
Just to clarify, `getSaveGroupIdentifier` and `allFiles` are used when transferring saves, but this is only possible if profile-saves are available, which is not the case for most games due to "limitations" of USVFS.

For the `getName`, I'll see if I can push it for 2.4.1. Ideally, the saves list should be refactored to be a proper view with columns for name, file, time, etc., but that might be a bit much for 2.4.1.

**Comment by erri120** [comment]
I'm guessing this line is responsible for the behaviour:
https://github.com/ModOrganizer2/modorganizer/blob/master/src/savestab.cpp#L195
