### ISSUE TITLE
SSE Mod Index is wrong.Console always displays "Can't find object."

### ISSUE THREAD

**Issue by lyne408** [ModOrganizer2/modorganizer#1463]
## Wrong Mod Index Issues

MO2 always displays wrong Mod Index in Plugins list panel.

And run `placeatme xx000xxx 1` in game console always get message like "Can't find object." due wrong Mod Index.

## Form Index Mechanism

[Data File Docs on creationkit.com](https://www.creationkit.com/fallout4/index.php?title=Data_File)

I read that *Data File Docs*, refer to SSEEDIT's Form Index and Load Order, get following info:

- There are four types of **Data Files**
- Form Index Priority of *Data Files*: Master > Plugin > Light Master > Light Plugin.
- Load Order isn't Mod Index
- Both **file extension** and **Record Flags** determine it's type.

    The items of first vertical colum are *file extensions*.
    
    The items of first horizontal row are *Record Flags*.

    |       | no ESM, no ESL |   ESM         | ESL          | ESM, ESL      | 
    | ----- |    ---        | -------      | ---          | ---            |
    | .esm  |  Master     | Master       | Light Master | Light Master | 
    | .esp  |  Plugin     | Master       | Light Plugin | Light Master  |
    | .esl  |  Light Master | Light Master | Light Master | Light Master |

**Comment by LostDragonist** [comment]
The main issue here is that MO assumes you have a sane load order in order for the mod index to be correct.  This is due to the fact that MO does not enforce any rules regarding load order until you try to move plugins.  This leads to the ability for plugins to be in impossible positions that would normally be rejected.

For now, if you don't know how to set up your load order, I'd suggest hitting the sort button or using LOOT.

**Comment by lyne408** [comment]
> 
> 
> The main issue here is that MO assumes you have a sane load order in order for the mod index to be correct. This is due to the fact that MO does not enforce any rules regarding load order until you try to move plugins. This leads to the ability for plugins to be in impossible positions that would normally be rejected.
> 
> For now, if you don't know how to set up your load order, I'd suggest hitting the sort button or using LOOT.


I may have described it vaguely. You may have misunderstood me.

The reason for the WRONG Form Index is that the mo2 skylimse plugin does not clearly distinguish Light Masters from Light Plugins.

**It mistakenly recognizes that Light Masters and Light Plugins have the same priority of load order and form index. But actually not.**

**Light Masters have higher priority than Light Plugins at both Load Order and Form Index.**

----

We know that, *plugins priority of MO2*, *Load Order*, *Form Index*, they are not the same.

The priority of a **good style** and correct load order is:

Masters & Light Masters > Plugin & Light Plugins.

*good style* means a Light Master should not depend on a Plugin.

In terms of game mechanism, the priority of Form Index is:

Masters > Plugins > Light Masters > Light Plugins.

----

I have read the source code of mo2 skylimse plugin. It does mark Master, Plugin and Light(Light Master), but it does not mark Light Plugin.

More commonly, a Light Master has **lower plugin priority** than a Light Plugin in MO2, MO2 recognizes that the Load Order and Form Index priority  of that Light Master is **lower than** that Light Plugin. This is a clear mistake.

## MO2 Mod Index Issue

![MO2 Mod Index Issue.jpg](https://staticdelivery.nexusmods.com/images/1704/53503831-1615752193.jpg)


## SSEEdit Correct Load Order and Form Prefix

![SSEEdit Correct Load Order and Form Prefix.jpg](https://staticdelivery.nexusmods.com/images/1704/53503831-1615752649.jpg)




----

**Comment by Holt59** [comment]
MO2 does not set your load order for you. There are a few rules that prevents moving some stuff but I'm pretty sure they are irrelevant here.

I still don't understand what you expect from MO2 in the current scenario. MO2 computes the index based on the priority, if the priority aren't right, then the index won't be, but MO2 is not responsible for your priority values. The index might not correspond to the actual index seen by the game but that should not matter since the value is purely informational as far as I know.

**Comment by lyne408** [comment]
> 
> 
> MO2 does not set your load order for you. There are a few rules that prevents moving some stuff but I'm pretty sure they are irrelevant here.
> 
> I still don't understand what you expect from MO2 in the current scenario. MO2 computes the index based on the priority, if the priority aren't right, then the index won't be, but MO2 is not responsible for your priority values. The index might not correspond to the actual index seen by the game but that should not matter since the value is purely informational as far as I know.

The priority of Load Order and Mod Index of Light Masters should higher than Light Plugins.
MO2 doesn't do this.

LOOT is just a utility to change the Load Order of plugins, the rules are controlled by it's Github repo, means single preset.
Many experienced users do not use LOOT, they sort mods and plugins manually.

Fine, thanks for all you developers of MO2.
I'd developed a utility [Mods And Plugins Sortor] to control priority and load order manually, but due to the wrong Mod Index displays in MO2 Plugins Panel, `placeatme xx000xxx 1` always can't get corresponding objects.

So next plan is fix the wrong Mod Index of MO2, just like fix some internal Skyrim SE bugs, by using ~~wrong logic~~.
So Open Source, personal user requirements, do it youself.

**Comment by Holt59** [comment]
You don't have to get angry and close your issue... We are only trying to understand the problem you're having. Basically your issue is that the Mod Index in MO2 is not right when the priority is "incorrect"?

As LD said, the Mod Index in MO2 is buggy and will only display proper Mod Index if you have correct priority. If you have light master after light plugins, then the priority is not right, but that's not MO2's fault, MO2 does not control the priority.

Yes, the Mod Index display should probably be fixed but, Open Source does not mean infinite resources. If you'd like to open a PR to fix the Mod Index display, then we'd happily accept it.

**Comment by lyne408** [comment]
> 
> 
> You don't have to get angry and close your issue... We are only trying to understand the problem you're having. Basically your issue is that the Mod Index in MO2 is not right when the priority is "incorrect"?
> 
> As LD said, the Mod Index in MO2 is buggy and will only display proper Mod Index if you have correct priority. If you have light master after light plugins, then the priority is not right, but that's not MO2's fault, MO2 does not control the priority.
> 
> Yes, the Mod Index display should probably be fixed but, Open Source does not mean infinite resources. If you'd like to open a PR to fix the Mod Index display, then we'd happily accept it.

I appreciate that you understand what I mean, but now, I don't have time to learn C++.

So, I'd to continue coding my personal project by using Node.js and TypeSript. As for GUI, may be Browser front-enb or Flutter...

If I am a main C++ developer, I may developed [Mods And Plugins Sortor] to bundle in MO2 SkyrimSE Plugin, yeah, that would be much convenient.

So another callback when new plugins added or after dragging plugins?
