### ISSUE TITLE
Project76 (Fallout 76 PC GamePass | Location: Program Files\ModifiableWindowsApps\Fallout 76)

### ISSUE THREAD

**Issue by Kelryth** [ModOrganizer2/modorganizer#1543]
**This template is useful to add basic support using https://github.com/ModOrganizer2/modorganizer-basic_games.** 

**If you are vaguely familiar with programming you can try following the instructions on that link to get something working yourself. If you have trouble with that please fill in this template.**

**Please provide the following information for the game (remove the optional lines you do not use):**

- **Name:** Fallout 76
- **Short name:** fallout76
- **Executable:** **Project76_GamePass.exe**
- **Data path:** Program Files\ModifiableWindowsApps\Fallout 76\Data
- **Documents path:** My Games\Fallout 76\
- **Saves directory [optional]:** My Games\Fallout 76\Saves
**Provide additional details regarding the game that could be required for the plugin.**
Same as the Retail version

**Comment by Al12rs** [comment]
We can't support game pass games since they have made them so that you can't start them from other programs for some security/isolation reason. Mo2 can't work if it can't start the game to inject the virtual file system. So it's basically useless. 
Also gamepass games will have much more issues with being modded for these reasons. I don't expect many mods to even work on the game pass versions.
