### ISSUE TITLE
Additional Install Information + Optional ESP view for Multiple Mods

### ISSUE THREAD

**Issue by explosivedeer** [ModOrganizer2/modorganizer#1562]
**Is your feature request related to a problem? Please describe.**
1.) 
While I'd hope troubleshooting CTD's are far in between the modding experience, I think it'd be useful to have some additional information attached to the list of mods. Downloading and installing a sheer number of mods is no easy task, and remembering the process is even harder. It'd be nice to have ways to re-trace your steps. When performing "merges" via MO2 the "Installed" status on downloaded mods is broken, thus making things a bit harder to verify.

2.)
When it comes to patches for mods, not all authors are consistent in their approach! Sometimes they'll include patches in their FOMOD installer, require you to download an additional file from nexus, or in some cases leave it to others who take a similar varied approach. I frequently find myself with FOMOD installers that offer patches for mods I will want to install later in the load order. To continue testing for any other issues, Optional ESPs need to be temporarily unticked, but this list can rapidly grow! It becomes rather difficult to keep track of the ones you've temporarily disabled.

**Describe the solution you'd like**
1.)
I think it would help tremendously to see a status indicator of a mod, and its "source." Statuses like: "Fresh-Installed", "Replaced",  or "Merged", and also a reference to the downloaded file(s) it came from. 

2.)
A window that can show all of the Optional ESPs, separated by mod, and filterable, with the ability to tick or untick.

**Describe alternatives you've considered**
2.) A flagging system where you can mark a mod in your list that needs attention later down the line, via color or flags.

**Comment by Al12rs** [comment]
We want to introduce ghosting plugins instead of making them optional (renaming them with .ghost at the end) which is more supported by other tools). It would allow us to show these plugins in the right pane with a checkbox perhaps or something like that.

Merging mods when installing is poorly supported as it's generally not the ideal solution anyway. I would advise to always install as a separate mod and then group/collapse them with a separator if they are too many. 

But I agree that the installed status thing breaks easily and we should track all the files that are installed in a mod instead of just the last one (though this requires changing the format of saving meta information, which means we will have two format to support).

For now, are you aware of the Notes column? It allows you to write whatever you want as a note to the mod. You can also define a color for the mod when right clicking a note column entry. More detailed Notes can be taken by opening the Mod information window, under the notes tab.

They way you can mark down merges and other operations.

**Comment by explosivedeer** [comment]
I'm excited to hear progress being made on a .ghost extension system, this should hopefully make the creation of large mod lists easier to test without needing their dependencies while also not having to worry about going back and digging through FOMODs to ensure patches for later-installed mods are present. 

Despite the added format requirement, I think it would be very worth the investment as this would help to ensure you know what is installed and what isn't. Despite knowing the lack of proper support for "merging" folders I wanted to give it a shot in an attempt to reducing the number of items in the list for better organizational purposes, so really this falls on me! Perhaps in addition to Replace / Merge / Cancel, a "create additional mod" function should be added that will automatically append a number to the end of the name as its not always obvious that a FOMOD installer will sometimes generate an identical name to a previously installed mod?

The Notes column alluded me! I should have looked for it it the column options. This should be more than enough for me to keep track of what I'm doing for the time being. Truth be told, while I do like the colored line options (especially for separators) will there be any plans to provide a way to disable color marks being displayed on the scroll bar? It conflicts a bit when trying to quickly scroll to any mods that are overwriting previous ones. I might just need a new pair of glasses though haha!

**Comment by Al12rs** [comment]
> will there be any plans to provide a way to disable color marks being displayed on the scroll bar?

Check under the MO2 Settings, Mod List, "Show mod list separator colors on the scrollbar".

**Comment by Al12rs** [comment]
I will close this issue since it's better to have a separate issue for each individual suggestion we discussed and we seem to already have issues open for each of these.
