### ISSUE TITLE
Change misleadiing description "Create files in mod instead of overwrite"

### ISSUE THREAD

**Issue by gitoss** [ModOrganizer2/modorganizer#1574]
**Is your feature request related to a problem? Please describe.**
It took me a long time to understand where files written by a configured tool are written to in the vfs.

A misleading description ""Create files in mod instead of overwrite"" contributed to that - because the files are only written to this mod folder if they don't exist in the vfs! So this is only an "overwrite redirect" option, and not a "never touch my original mod folders, put all written files in the configured folder" option.

**Describe the solution you'd like**
The option should be named "Redirect overwrite into mod"

**Describe alternatives you've considered**
Not submitting this bug ticket because it's just me that doesn't understand how MO2 vfs works

**Additional context**
There should be a red, blinking description somewhere how the vfs overwrite works - I had to turn to reddit for that: https://www.reddit.com/r/skyrimmods/comments/lcyxec/mod_organizer_2_where_do_the_nemesis_generated/

**Comment by AnyOldName3** [comment]
The new name you're proposing is potentially even more misleading than the current one. *Technically* the current string is accurate as newly-created files *do* end up in the mod, and any other files don't, whereas with *redirect overwrite into mod*, it's pretty easy to misread that as any files that get overwritten end up in the new mod instead of editing the original. We're well aware that this problem already exists with the default overwrite mod's name, but that doesn't make it a good idea to copy the problem elsewhere in the hope that people will realise working the same way as the overwrite mod means what it actually means.

Maybe a better replacement would be *Create new files in mod instead of overwrite directory* or something like that which is more explicit that it just affects new files.

Super long-term, I still hope we can talk Kerber into making KxVFS have a copy-on-write mode that we can integrate so people can do their modding with the isolation they often think they're getting, while still allowing them to switch to USVFS when playing the game (as they won't be editing files and the speed will be better).

**Comment by gitoss** [comment]
+1 für the the CoW VFS you mentioned

I admit I didn't really rtfm, but I did expect MO2 not to touch my original mod folders when I enable the "Output files to ___ folder" checkbox.

I'll close this issue because you've got the problem and potential solutions on your radar already - thanks!
