### ISSUE TITLE
F4SE Unable to launch

### ISSUE THREAD

**Issue by TheMaverick61** [ModOrganizer2/modorganizer#1577]
Hi,

I have an issue with launching F4SE through MO2 it will not launch Fallout 4,  F4SE launchs fine from it's own exe,  But not through MO2?
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/7015330/mo_interface.log)
[usvfs-2021-08-19_14-39-06.log](https://github.com/ModOrganizer2/modorganizer/files/7015353/usvfs-2021-08-19_14-39-06.log)

Hope You can Help

**Comment by Al12rs** [comment]
To check whether the issue is related to one of the mods installed or your ini settings, see if it keeps happening in a new empty profile:
https://cdn.discordapp.com/attachments/403979692501106688/524939782435110924/unknown.png
https://cdn.discordapp.com/attachments/403979692501106688/524940397643038740/unknown.png

Also make sure you don't have any mods installed in actual game folder, and test if the issue happens outside of Mo2 if you didn't already.

**Comment by LostDragonist** [comment]
You're missing the F4SE Address Library.  You need to have all the requirements for your mods if you expect them to work right.
