### ISSUE TITLE
M02 wrong texte

### ISSUE THREAD

**Issue by 007chabp** [ModOrganizer2/modorganizer#1589]
on categories item : ( Voice) goes on wrong indication ( tattoo ) description or nothing still blank.
Need to be rectified.
version 2,4,2
have a good day

![Capture](https://user-images.githubusercontent.com/90108807/133477019-a2f4910b-b11c-401c-8a5b-60a84e45c5e6.PNG)

**Comment by MarkKoz** [comment]
This is because the tattoos and voices categories have the same ID, `39`:

https://github.com/ModOrganizer2/modorganizer/blob/e78f46cc9ec440a04e8421d150d114db2ca6810d/src/categories.cpp#L215
https://github.com/ModOrganizer2/modorganizer/blob/e78f46cc9ec440a04e8421d150d114db2ca6810d/src/categories.cpp#L235

This conflict was introduced by https://github.com/ModOrganizer2/modorganizer/commit/581a8871c62a05d48a45059e6e611871be3f6361
