### ISSUE TITLE
Windows 11 installation of mo2 will conflict with this file and will not work

### ISSUE THREAD

**Issue by mxhyyj** [ModOrganizer2/modorganizer#1624]
Installing mo2 under windows 11 will conflict with this file, which is named C:/ProgramData/A- Volute/AVolute.Nahimic/Modules/Scheduled/x64/ASM.Plugin.AudioDevProps2.dll. This file comes with the system and cannot be deleted.

**Comment by mxhyyj** [comment]
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/7681721/mo_interface.log)

**Comment by AnyOldName3** [comment]
Nahimic is some software that comes with certain MSI hardware that's supposed to make audio better. It breaks other applications, though, including MO2, so you can't use MO2 while it's installed. Our recommendation is to uninstall Nahimic, like the log says, as obviously we think our software's more useful.

The investigation we've done so far suggests it's Nahimic that's breaking things rather than MO2, so if you want to use both, your best bet is to nag its developers until they fix it.

**Comment by 352** [comment]
Nahimic also ships with and is installed by ASUS software with it's 
mainboards;  I've used both with MO2 for years without issues.  MO2 
works just fine (with Skyrim and SkyrimSE).  I'm using the latest 
development versions of MO2.

**Comment by LostDragonist** [comment]
Thanks for the feedback @352!  Unfortunately, other users aren't as lucky so the warning will stay in place for now.  If you're not having problems with MO2, it's suggested to ignore any warnings or errors in the text log. They are more for diagnosing why problems are occurring than for detecting that problems are occurring.
