### ISSUE TITLE
Two Oblivion mods with BAIN wizards not handled properly

### ISSUE THREAD

**Issue by Javic36** [ModOrganizer2/modorganizer#1688]
These two mods for Oblivion involve BAIN wizards:

https://www.nexusmods.com/oblivion/mods/49966
https://www.nexusmods.com/oblivion/mods/19628

Neither is properly installed by MO2 2.4.4. (It's my understanding that MO2 should now handle BAIN wizard installers.) In both cases, the wizard runs and executes a few steps, and no error is reported, but several required files are not installed, and for 19628 several wizard steps are skipped.

I'm running MO2 under 64-bit Windows 7 SP 1.

**Comment by Holt59** [comment]
Could you check with the following version of the plugin? Simply extract the `installer_wizard` folder into the `MO2/plugins` folder and overrides everything Windows asks you.

[installer_wizard.zip](https://github.com/ModOrganizer2/modorganizer/files/8528773/installer_wizard.zip)

**Comment by Javic36** [comment]
Thanks for the quick reply!

Colored Quests (49966) is now working properly.

Unfortunately, Animated Window Lighting System (19628) still does not appear to work correctly. The file "wizard.txt" includes questions about other mods that might be installed (e.g., "Do you use Qarls Texture Pack III?" and "Do you use RAEVWD?") but those questions are never asked. (BTW I'm not an expert on wizards, but I'm following a modding guide that says how to answer the questions, so I know they're supposed to appear.)

**Comment by Holt59** [comment]
Could you link the tutorial? Because if I use the default options I do get the questions you're mentioning in the install wizard.

**Comment by Javic36** [comment]
By "tutorial" you mean the modding guide I'm following? It's here: https://www.nexusmods.com/oblivion/mods/49898.

But I don't think that'll help. It says mostly to accept the default options. (And note it has two sets of instructions for this mod, one if using LOD and another if not. I'm using LOD.) But regardless of what options I pick, I never see the questions about RAEVWD, Qarls, or Bomrets. Here's what I see and do in the wizard:

Page 1: Options: pick 'Advanced Smoking Chimneys' (default) and click Next.
Page 2: Options: pick 'Install default window types' and click Install (there is no "Next" button).

That's it. Never asks about RAEVWD, Qarls, or Bomrets.

Are you and I using the same version of MO2? Mine says 2.4.4 in the title bar and Help > Update Mod Organizer is disabled so I assume this is the latest. Is there something else I can check to ensure my MO2 installation is correct and up-to-date?

**Comment by Javic36** [comment]
Update: I just noticed that when I run the wizard as described, I see the following in MO2's transcript window:

[2022-04-22 23:22:40.022 W] [fomodinstallerdialog.cpp:378] "The value exists but was not matched."
[2022-04-22 23:22:40.022 W] [fomodinstallerdialog.cpp:378] "The value exists but was not matched."
[2022-04-22 23:22:42.154 W] [fomodinstallerdialog.cpp:378] "The value exists but was not matched."
[2022-04-22 23:22:42.154 W] [fomodinstallerdialog.cpp:378] "The value exists but was not matched."
[2022-04-22 23:22:44.458 W] [fomodinstallerdialog.cpp:378] "The value exists but was not matched."
[2022-04-22 23:22:44.458 W] [fomodinstallerdialog.cpp:378] "The value exists but was not matched."
[2022-04-22 23:22:44.458 W] [fomodinstallerdialog.cpp:378] "The value exists but was not matched."
[2022-04-22 23:22:44.458 W] [fomodinstallerdialog.cpp:378] "The value exists but was not matched."
[2022-04-22 23:22:44.458 W] [fomodinstallerdialog.cpp:378] "The value exists but was not matched."
[2022-04-22 23:22:44.458 W] [fomodinstallerdialog.cpp:378] "The value exists but was not matched."
[2022-04-22 23:22:44.459 W] [fomodinstallerdialog.cpp:378] "The value exists but was not matched."
[2022-04-22 23:22:44.459 W] [fomodinstallerdialog.cpp:378] "The flag 'bDefault' did not match 'On'"

**Comment by Holt59** [comment]
This is from the FOMOD installer, not the Wizard one - the mod actually contains both a Wizard and a FOMOD.

The guide probably uses the Wizard one since it uses Wrye Bash, which is why you don't get the same options. In the end, you have two options:
- Use the FOMOD one and adapt the question - The FOMOD is probably equivalent to the Wizard, the question are just not in the same order (e.g., the QTP3 and RAEVWD are on the first page directly).
  - The error in the logs on the FOMOD are not important, many FOMOD are not 100% properly written, hence the errors (which should be warning or even debug logs... )
- Change the settings of the Wizard installer (Tools > Settings > Plugins) and set "prefer_fomod" to False so that the Wizard installer is chosen when both are available.

**Comment by Javic36** [comment]
Thanks. Turning off 'prefer_fomod' worked. I usually want to use the wizard if there is one. Any down side to having this option off?

Also, I'm still getting one error:

**Comment by Holt59** [comment]
The option says what it - FOMOD are more used and usually more tested than Wizard installers, but the Wizard installer is probably more robust than the FOMOD one, so, your choice. Since you're following a guide that uses Wrye Bash I'd say that it should be better to prefer the Wizard over the FOMOD.

The error is fine (should also be a warning) - It's because there is a slight mistake in the Wizard file, but there is no impact on the installation.

**Comment by Javic36** [comment]
OK. Thanks.
