### ISSUE TITLE
Add support for top-level usvfs hooks

### ISSUE THREAD

**Issue by KenJyn76** [ModOrganizer2/modorganizer#1753]
I prefer MO2 to Vortex, but I use Vortex currently to MO2 because I like to keep my game directories clean. MO2 does this better for the data folders, but the top-level of the game folder is a mess. Vortex is able to install mods for the top-level of the game folder by assigning a mod type to every mod, and Engine Injectors put the files on the top level, keeping script extenders and other mods that hook the game's executable separate, as well.

Can a similar solution be added to MO2?

**Comment by AnyOldName3** [comment]
Technically, USVFS can do it, but if it does, it won't let you do anything useful. Nearly everything that can be installed in the root directory needs to be loaded really early on, and USVFS can't load that early, so from the game's perspective, the files won't exist yet when it tries to load them, and then they'll appear later once they're useless.

Instead, there are root builder plugins available for MO2 which temporarily copy or symlink files into place instead of using USVFS. I *think* at least one of them can use USVFS, but doesn't by default as it doesn't achieve anything useful.

**Comment by KenJyn76** [comment]
Thank you for the explanation! A native support for this would be nice, but the plugin sounds like an elegant solution to me. I didn't even remember there were plugins at all, to be honest. 

Thanks again :)
