### ISSUE TITLE
Bodyslide batch build into new files fails

### ISSUE THREAD

**Issue by bluebuiy** [Modorganizer2/modorganizer#178]
# The problem
When there are no files to overwrite, batch building in bodyslide fails to write the built outfit meshes into overwrite.  It does create the meshes file.
If I complete the directory path (in this case, create meshes/DX/MiniArmorsCollection/Armlets/EmfyCleric/), it successfully writes the mesh files that go in this location.

# RePro
Install [this conversion](https://www.nexusmods.com/skyrimspecialedition/mods/14087), but DO NOT have the base mod installed.
Run x64 bodyslide.
Batch build the Emfy Cleric group.

# Environment

* Mod Organizer Version that exhibits the issue: All
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: win 10

# Details
Using x64 bodyslide.

# Link to Mod Organizer logs

[mo and usvfs logs](https://gist.github.com/bluebuiy/2edf3002138f57e8b4fb667b1bc52d94)

**Comment by Silarn** [comment]
Now, I'm not sure why creating the directory path would change anything but BodySlide is known to use a writing method that MO's virtualization is currently unable to catch.

Because it opens and writes to the existing files directly, those meshes will be directly written by BodySlide instead of writing to overwrite. Currently MO only places files into overwrite if it's told to create a new file. (Either via a copy or a forced overwrite.) Many tools work this way which is why there usually isn't a problem.

A workaround is to hold 'Left-Ctrl' while pressing the build buttons which instructs BodySlide to output into a custom directory.

**Comment by erasmux** [comment]
This has been fixed in the usvfs 0.3 version. Please verify this.

**Comment by Silarn** [comment]
This is available on our Discord server listed in the repository description.
