### ISSUE TITLE
%localappdata%\ModOrganizer clarifications in docs or inside the program

### ISSUE THREAD

**Issue by AndyScull** [Modorganizer2/modorganizer#179]
So, I made two instances, for FO4 and SkyrimSE.
After changing basedirectory folder and successfully moving instance to E:. I deleted (logically thinking) redundant instance folder from user profile (like, I did change it's location to other drive, duh, let's clear old logs and other leftovers). Maybe that can be documented better for future users? Like some documentation on folder structure or straight warnings in paths screen? Right now, every sane person will assume that moving basedirectory means moving the whole instance directory, and anything left in old path is just some leftover junk)

**Comment by Silarn** [comment]
Correct, instance mode does still store some core settings files within AppData to tell it where to look for the custom install locations etc. These directories also exist to tell MO what instances already exist. (Creating a directory manually will create a phantom instance.)

The specific directories you move in the settings can be deleted - though I do think we should consider fixing up this system to prompt to move these directories to the new location/delete them. And there are some issues with MO properly refreshing mod lists/data when the location is changed.

**Comment by AndyScull** [comment]
So, just a suggestion - maybe MO2 should always ask user for path to storage folder when new instance is created? That way, metadata would a;ways be stored in user profile, and all data folders would be somewhere on user's 'data' drive. If user really wants to bloat his profile on C:, they can always manually point it to %localappdata%\.
From my POV it's bad practice to store GBs of data in user profile folder (even though it's in Local\), because of 1) some backup software backups whole profile instead of just 'roaming' folders like %appdata% and documents; 2) quite often disk C is a small-mid size SSD with very limited space.
Maybe MO2's default  storage path could be game's installation folder or Documents\My Games\ path?

**Comment by erasmux** [comment]
That is the windows convention, MO didn't invent that. The MO code just asks Qt for the application data directory, and per windows conventions, it returns us the  %localappdata%\ModOrganizer.

That said, **in theory** I do think it would be a good idea to have a global setting which can set the root folder where MO stores instances. This could be stored in the registry so that it affects all current and future installs.

In practice, this could be a very challenging and error prone change as one would need to find **all** the places the code refers either to the Qt application data folder or to the %localappdata% folder in other ways (if there are such) and fix all of them. If we miss some....

**Comment by SuperSandro2000** [comment]
I think this added that. Will be in the next release. https://github.com/LePresidente/modorganizer/commit/c1421d07345617e7776dd8bdf0aec4dbef52a72a
