### ISSUE TITLE
Creating New Global instance for Subnautica - Application Failure

### ISSUE THREAD

**Issue by raydleemsc** [ModOrganizer2/modorganizer#1833]
## The problem:
Creating New Global instance for Subnautica, but error dialog instead - 
![ModOrganizer-Error_19_14-36-24-799](https://github.com/ModOrganizer2/modorganizer/assets/12947065/1995d9f7-bf97-43c1-9b33-977545e90ccc)

## To Reproduce:
1. create new global instance for subnautica - 
![steamwebhelper-Properties_-_Subnautica_19_14-48-26-485](https://github.com/ModOrganizer2/modorganizer/assets/12947065/17bf7509-236d-4427-b438-2286b5ac6139)
2. mo2 then exits completely

## Environment:

* Mod Organizer Version v2.4.4
* Desktop OS/version used to run Mod Organizer:
* Edition	Windows 10 Home Single Language
Version	22H2
Installed on	‎07/‎Aug/‎2020
OS build	19045.3086
Experience	Windows Feature Experience Pack 1000.19041.1000.0

## Details:
Successive restarts exhibit the same error with no option to change instance or fix the issue. Preferred behaviour *should* be to not fail on non-essential files as the game does load with no issues without the file in the place that mo2 requires it.

## Link to Mod Organizer logs:
Cannot open mo2 to turn on logging, and no log folders or files found in mo2 install location or sub-folders (windows search for 'log')

### USVFS:
None found

### MO Interface:
None found

**Comment by raydleemsc** [comment]
The initial create instance causes the error, and subsequent restarts of mo2 *only* exhibit the error with no other dialogs available

**Comment by raydleemsc** [comment]
Same issue replicated on linux mint 20.2 using wine

**Comment by raydleemsc** [comment]
uninstall>restart>reinstall - same error

**Comment by ZashIn** [comment]
This is already fixed in MO 2.5: ModOrganizer2/modorganizer-basic_games/pull/92

**Comment by raydleemsc** [comment]
Looked through https://github.com/ModOrganizer2/modorganizer-basic_games/pull/92 - but v2.5 not mentioned

maybe https://github.com/ModOrganizer2/modorganizer-basic_games/pull/116 and https://github.com/ModOrganizer2/modorganizer-basic_games/pull/119 are more relevant and recent

But v2.4.4 is still the current release awaiting https://github.com/ModOrganizer2/modorganizer/milestone/23

**Comment by ZashIn** [comment]
@raydleemsc the `basic_games` version included in v2.4.4 is a bit old by now. MO 2.5 beta release can be found on [the discord server](https://discord.gg/ewUVAqyrQX).
Since MO 2.5 switched from PyQt5 to PyQt6 and made some additions to the plugins API, you cannot simply use the latest basic_games changes in MO 2.4.
For 2.4 you can try [this release](https://github.com/ZashIn/modorganizer-basic_games/releases/tag/subnautica-plugin-v2.1), which got merged into master. There might be some additional fixes after it, but the issue with `doorstop_config.ini` is fixed with better mod support .
For newest version, please try the MO 2.5 beta.
