### ISSUE TITLE
Can't install mod if no categories are available

### ISSUE THREAD

**Issue by johannes-z** [ModOrganizer2/modorganizer#184]
# The problem

I deleted all the default categories of my MO fallout 4 installation. When I now download a mod via MO and try to install it, the log says `nexus category id 9 maps to internal 8` and I get a popup saying `invalid index 8`.

# Environment

* Mod Organizer Version that exhibits the issue: MO v2.1.1 (Revision c1a56f7)
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Mod Organizer: Windows 10 Pro v1709 (build 16299.125)

# Details

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs

## USVFS

not applicable

## MO Interface

```
15:01:11 [D] 1 orphaned meta files will be deleted
15:01:19 [D] nexus category id 9 maps to internal 8
15:01:24 [D] nexus category id 9 maps to internal 8
15:01:31 [D] nexus category id 9 maps to internal 8
15:02:06 [D] 1 orphaned meta files will be deleted
15:03:06 [D] nexus category id 9 maps to internal 8
```

**Comment by Silarn** [comment]
I guess we should create a fallback in case a user removes all default categories. I'm planning to partially revamp the category generation anyway since it's a bit flawed presently and not all Nexus IDs map to the same category for each game. (The currently implementation is unable to handle re-used Nexus Category IDs for different games.)

**Comment by PixilatedClarity** [comment]
Did anyone find a fix for this yet? I tried reinstalling MO2 but to no alas...
