### ISSUE TITLE
Skip the Discord requirement for participation

### ISSUE THREAD

**Issue by seanvikoren** [ModOrganizer2/modorganizer#1881]
Placing the alpha and beta versions behind a virus wall (Discord) feels anti 'open source' to me.

Not having access to any of your reasons, I will simply ask this of the team:
Re-comit yourselves to open source, and publish your betas on github.

Please.

**Comment by seanvikoren** [comment]
Hey mouse.  What's up?

**Comment by seanvikoren** [comment]
Nice to meet you Holt.

**Comment by Al12rs** [comment]
As already explained in the other issue, development builds are meant for testing 
and getting feedback on specific changes.

These builds are broken the majority of the time and they are not ready for general use.

MO2 updates itself to GitHub beta releases if the user selects "install beta releases" in the settings.

We don't want that, as thousands of people could get broken installs "over the air" with no knowledge on how to roll back or no real understanding that betas can brik your mod setup.

In addition, making a new GitHub beta release is a very long and tedious process since we have 60+ repositories to manage.
This isn't conducive to quick development iteration and fixes.

We often post multiple builds a day while trying to fix a bug or improve a feature.

- Post build, 
- our testers check it out, 
- tell us what is broken or needs improvement using real time chat, 
- we ask more info (logs details etc) in real time,
- we try to fix it,
- post a new build, 
- ping the guy that was having issues,
- see if that fixed it,
- repeat.

This is simply not possible on GitHub since it is much slower interaction.
Plus, as I mentioned, we don't want to have Dev builds be installed by the Mo2 auto updater.

We do sometimes create actual Beta releases on GitHub, but only when we are close to actual releases and are very confident the code is stable and will not cause issues when upgrading.
That is not the case for the current dev builds, so they are on discord with the purpose to be tested by our testers.

Anyone can join and become a tester if they wish, but we have clear disclaimers on our devbuilds warning about the risk, and if they do encounter problems we actually get to know about it immediately, not discover it a few days or weeks later after they posted about on some Reddit.

Also a lot of people don't have GitHub accounts to post about issues.
Discord is realtime and used by much more poeple, not just developers, and we need help from non developers for testing.

Mo2 doesn't have a test suite for regression testing, so we have to rely heavily on manual testing to find bugs.

**Comment by Silarn** [comment]
The dev builds are also not black boxes. I rarely push builds that have not had their code pushed to a feature branch first. I usually only provide builds after my own first pass at basic functionality and bug testing. So to make an accusation that the project is 'not open source' when we are literally providing the sources (along with every dev build and in every one of our repos) and openly accepting public pull requests - merely because we don't publish every incremental build we produce to GitHub - is frankly silly.

**Comment by seanvikoren** [comment]
Well, thank you both for your thorough explanationtions.
I did not comprehend the scope of your doings.
And you are right Sil. That was silly.

But please understand, after many weeks of working on mod things, you are the first two civil insiders I have met.
It looks like an angry castle from the outside.

It sounds like I can put my complaining ass to work, at least as a tester.
Thank you for chatting.

I can probably find the servants entrance on my own. ;)
See you on the inside, unless you see me first.

**Comment by AnyOldName3** [comment]
> But please understand, after many weeks of working on mod things, you are the first two civil insiders I have met.

It wouldn't be very hard at all for people to read the way you're starting these discussions as uncivil, and once that's happened, only a very chill person is going to remain civil with their response. If you get on people's bad side right from the get-go, you'll only ever see the worst side of them.

Also, you seem to have misunderstood some of the goals of free and open source software. The GPL licence that MO2 uses is explicitly designed to allow private and limited releases as long as the source code's made available to everyone the binary's made available to, and we don't put restrictions on what people do once they've got them as long as they comply with the GPL. We could even charge for access to the betas and dev builds, and that would be entirely okay according to organisations like the Free Software Foundation (although anyone who bought them would be allowed to share them with anyone who hadn't, so it wouldn't be a good income stream). We don't do that, though. We just keep the betas and dev builds tucked away so we can get a manageable amount of high-quality feedback about them rather than get overwhelmed with support questions from people who'd be better off using a release build.

As for Discord being the place they end up, we're aware that it's not ideal locking them behind a proprietary platform, but most of our users already use Discord, and Matrix's moderation tools are still lacking, so if we were to have a Matrix bridge or move the entire thing over to Matrix, we'd be overwhelmed by spam unless we made it invite-only, at which point it would be an even bigger hurdle for most people than the Discord already is.

**Comment by seanvikoren** [comment]
One can always improve on manners.
I am certainly no exception.
I did say, that in the absence of knowing any reasons.
And you all gave me great reasons.
Regarding freedom; I was referring to 'like a bird', not 'like a gpl'.

Thank you for chatting.
I do look forward to making some contribution.

Cheers,
Sean
