### ISSUE TITLE
MO won't launch

### ISSUE THREAD

**Issue by The-Rogan-josh** [ModOrganizer2/modorganizer#1942]
## To Reproduce:
Bit thin on the ground here, unfortunately. sorry.

## Environment:

* Mod Organizer Version that exhibits the issue: Ver 2.4.4.0 & Ver 2.5
* Last Mod Organizer Version that did not exhibit the issue (if applicable): N/A. though i had no trouble running MO on my laptop.
* Desktop OS/version used to run Mod Organizer: Windows 10, latest update.

## Details:
This problem is on a new PC build, everything is up to date. I can't find any information about this issue either.
The only thing i can think of that is causing an issue is that my only monitor is an XPpen tablet screen (Drivers are up to date too) run through an HDMI cable. I'd really like some advice before i go and drop money on a new monitor to test this out though. Many thanks.

**Comment by fitzgee1** [comment]
I'm having the same issue, no results so far :(

**Comment by The-Rogan-josh** [comment]
Yes it's frustrating. I haven't found anything yet either.
I've tried a portable and global install, tried via stalker GAMMA modpack, tried via wabbajack. Same problem. There is precious little info to work on.

**Comment by Halliphax** [comment]
Same thing here, brand new PC build on Windows 11 (problem happened on both 22H2 and 23H2 updates). Migrated all the Mod Organiser stuff over to the new PC and saw the problem, tried installing from fresh as well.

Opening from the Start Menu leads to the process floating in the background, if I kill it and reopen from Start Menu it'll finally open. Same thing happens when opening a download link from Nexus, just hangs until it's killed but it'll open fine on subsequent opens. 

Unsure if the issues are related but throwing my hat in anyway. Problem occurring on MO 2.5.0

**Comment by Halliphax** [comment]
Lads, try downgrading to a previous version and then upgrading again (I'd recommend taking some backups) - seems to have worked for myself.

**Comment by The-Rogan-josh** [comment]
Hi everyone,

i've fixed my issue with this and want to document it for future google searches.

Primarily the issue was that my AMD APU was interferring with my GPU, causing this issue (and another issue which lead to the solve). I disabled the AMD integrated Graphics via device manager > display adapters. 

Kind of embarrassed that it took me this long to solve it but hopefully it's useful to the next person searching for an answer.
