### ISSUE TITLE
FO4 save files suddenly disappeared.

### ISSUE THREAD

**Issue by RCplasmatron** [ModOrganizer2/modorganizer#1974]
Mod organizer 2 refuses to read any of the saves I have so when I load the game, all my saves are gone despite the folder that MO2 normally reads still has all the saves, I've tried looking everywhere to see if the folder directory for the saves have changed and even used save file manager and it still acknowledges that my saves are still there.

I haven't done anything unusual to make this issue occur however I have noticed when I created a new save, it's using FOS save files rather than F4SE files.

If you have any questions for me, please let me know.

Thank you.

**Comment by Cooker16** [comment]
MOD organizer not recognizing fallout 4 saves F4SE Type only FOS type

**Comment by RubberDuck01** [comment]
Can confirm, this has just happened to me.

Usually, I create only one save at the start of the game and then overwrite it, but every so often I create a new _hard_ save just in case. I created a new _hard_ save yesterday and now all my saves are gone from MO2 but are still located in 'My Games\Fallout4\Saves' (only F4SE saves are there).

I tried the following:
- restart MO2 as Admin - didn't work, I'm an administrator on my system
- enable profile-specific saves
- disable profile-specific saves

None of the above seemed to work.

Any help is much appreciated, thanks!

**Comment by RubberDuck01** [comment]
> Can confirm, this has just happened to me.
> 
> Usually, I create only one save at the start of the game and then overwrite it, but every so often I create a new _hard_ save just in case. I created a new _hard_ save yesterday and now all my saves are gone from MO2 but are still located in 'My Games\Fallout4\Saves' (only F4SE saves are there).
> 
> I tried the following:
> 
>     * restart MO2 as Admin - didn't work, I'm an administrator on my system
> 
>     * enable profile-specific saves
> 
>     * disable profile-specific saves
> 
> 
> None of the above seemed to work.
> 
> Any help is much appreciated, thanks!

**Found a temporary solution!**

The problem is that My Games directory contained only .F4SE save files and no .FOS files were present. To fix this, you can do the following:

1. Go to Steam\userdata\{SteamAccountId}\\**377160**\ac\WinMyDocuments\My Games\Fallout4\Saves.
2. Copy all the save (.FOS) files from there.
3. Paste the copied files to your My Games\Fallout4\Saves directory.
4. Refresh MO2.
5. Done, MO2 should now display your saves properly.

_Note: **377160** is the Id of Fallout 4. You can check this yourself by visiting the Steam Store page and examining its url._

I don't know what caused this issue, it's a first... What's more, I've got Steam's sync feature disabled so I don't understand what went wrong. I'll have to dig a bit deeper.

Hopefully this helps!
Take care!

**Comment by RCplasmatron** [comment]
Thx RubberDuck01, I managed to find my old saves and transferred it to MO2 so I can play my load again, Appreciate the help.

**Comment by Cooker16** [comment]
Thanx also it worked :D
Take care
