### ISSUE TITLE
mo2 wont launch

### ISSUE THREAD

**Issue by yapovelli** [ModOrganizer2/modorganizer#1992]
## The problem:
I recently reset my pc and now mo2 won't launch or start, tried reinstalling multiple times and downloaded the latest python version and it still won't work... it's not showing up on task manager either, any suggestions? thanks.

**Comment by yapovelli** [comment]
worked by running it as administrator.

**Comment by AnyOldName3** [comment]
No, that's not a fix. Running buggy software as an admin is like giving a toddler an uzi because you're irritated they're shooting you with a nerf gun. There's no reason to think it would help, but obviously means the thing that's not doing what it's supposed to has much more power to accidentally break things.

Also, where are people reading that installing Python would do anything to help MO2? It won't make any difference to anything. We'd like to know so we can get whoever's recommending it to stop recommending it.

If you come to our Discord server, linked in the main readme, someone can probably suggest a more reliable solution to your problems.

**Comment by yapovelli** [comment]
Yeah, I just had to restart my pc one time and everything perfectly works now. Maybe it wasn't working because I directly downloaded mo2 after resetting my pc and didn't even bother to restart it. And for the python thing, I thought it was the language causing it not to start since mo2 installs a python plugin and I didn't have python at first and decided to install it but turns out that wasn't the case. Thanks for taking your time to answer though, I appreciate it.
