### ISSUE TITLE
Bug: SkyrimSE/SKSE64 would not see most plugins after a few mod renames

### ISSUE THREAD

**Issue by pressure68** [Modorganizer2/modorganizer#202]
# The problem

Mod Organizer 2 / SKSE64 / SkyrimSE had been working perfectly for weeks. One night I installed a mod just to check it in SSEEdit, but I disabled it again before loading the game. I also renamed 2-3 active mods with notes for later. The virtual data structure and plugin load order were exactly the same as before, but I found this after:
 - starting the game via the SKSE64 loader would give an error on save load saying that almost all the plugins were missing
 - SSEEdit would load all plugins just fine with no issues
 - starting SkyrimSE directly would load all plugins just fine, but of course I got several errors about SKSE64 not running

I tried reinstalls of both SKSE64 and MO2, to no avail. I also tried renaming the mods I changed back, but I may have missed one. I ended up restoring a backup of the MO2 folder which did resolve the issue, but now I'm concerned about renaming active mods in the future.

# Environment

* Mod Organizer 2.1.1 (latest on nexusmods)
* Skyrim SE 1.5.23
* SKSE64 2.06
* Windows 10 x64, build 1709
* MO2 folder - "D:\Mod Organizer - SSE"
* SkyrimSE folder - "D:\Steam\SteamApps\common\Skyrim Special Edition"

# Details

see above

# Link to Mod Organizer logs

My apologies, but the restore to resolve the issue wiped any logs generated while the issue was occurring.

**Comment by Silarn** [comment]
There does seem to be some reporting that certain mods can cause skse to fail. I'm not really sure what's causing this because the same mods can work fine for other people. However, there is active development being done on the virtualization system and hopefully these kinds of issues can be resolved.

The best help would be to work with erasmux on Discord to see if he can identify your issue. (Or perhaps even just see if the new beta version of the usvfs dll fixes your issue.)

**Comment by Silarn** [comment]
Are you able to replicate this with recent dev builds? Closing if no response.

**Comment by pressure68** [comment]
Hi Silarn, I had the event reoccur later with the same version and just did a full restore again, but have not had the opportunity to test later builds. If others have reported improvements on this issue with them, then feel free to close this report.
