### ISSUE TITLE
Plugin problems

### ISSUE THREAD

**Issue by KopisGaming** [Modorganizer2/modorganizer#324]
#Problem

I have an issue where the UI is reporting a potential problem with my setup because of plug-in's not being loaded and the reason why its not loading is because it thinks that there is an outdated version of python or missing dependencies. I dont know how this is possible, I completely uninstalled the old MO (version 2.0.7) and installed the newest one (2.1.2), so it shoudn't be outdated. And I had installed the python in the installer so it isn't missing.

# Environment

* Mod Organizer Version that exhibits the issue:  Version 2.1.2
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): Version 2.0.7
* Desktop OS/version used to run Mod Organizer:  Windows 10

#Details

The missing plugin's are as follows : 
  -- diagnoseBasic.dll
  -- checkFNIS.dll
  -- bsaExtracter.dll
  -- gameOblivion.dll
  -- gameSkyrim.dll
  -- installerBAIN.dll
  -- installerFomod.dll
  -- installerBundle.dll
  -- installerNCC.dll
  -- installerManual.dll
  -- installerQuick.dll
  -- NMMImport.dll
  -- previewBase.dll
  -- proxyPython.dll

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/KopisGaming/afd82f1546ab9f83d3e6c545cfe714e2

## MO Interface
https://gist.github.com/KopisGaming/45dd77c2205a47cc2744c6a9bc7f3c5f

**Comment by AnyOldName3** [comment]
Mod Organizer can break when inside the game directory. Usually it's more subtle than this, so I strongly suspect you've got something else going on, too, but moving your MO installation is likely to prevent further issues down the line, so I'd start with that.

Specifically regarding your plugin issues, I've seen the same error code before when something tried to load a folder thinking it was a DLL. Can you look in your plugins folder and double check that everything is an actual DLL file?

**Comment by KopisGaming** [comment]
I was suggested to put MO inside the game directory. Gopher over on YouTube (a well known and respected member of the community) made a tutorial for MO and he quite clearly stated that was how he'd recommend installing MO. Has that changed since the video tutorial was made?

I checked the DLL folder and found a sub-folder called imageformats with a bunch of dll's inside. Move thee dll files to the main DLL folder?

**Comment by KopisGaming** [comment]
Right. Apologies, just me being dense. :P

I took a look at the plugin's folder and found a data folder inside along with some dll's. This data folder has its own series of files too. 2 Py, 2 Pyo, a dll, json, and Pyd files and another sub-folder. What do you want me to do?

**Comment by AnyOldName3** [comment]
Basically just check that the DLLs for the plugins you're getting errors about are actually DLLs. This includes them existing in the plugins directory and having a sensible file size and being the same as the ones in the MO release archive.

**Comment by KopisGaming** [comment]
Yeah, their all dll's. This is weird. :/

**Comment by AnyOldName3** [comment]
And you've checked that they're identical to the ones in the MO archive you downloaded? I.e. You've checked they've got the same md5 hash or something.

**Comment by KopisGaming** [comment]
I downloaded the installer from the SSE Nexus. Not an archive.

**Comment by AnyOldName3** [comment]
If you have 7zip, you can open the installer as if it was an archive anyway, so maybe give that a try. If you do, then you can find a plugin DLL, right click on it, and under the CRC option, there'll be a range of hashes you can take of the file. If you take the same hash of the version in your MO install, and it's different, then you've found the cause of the problem.

The theory that I'm working under is that for whatever reason, the DLLs for those plugins are broken. This could be because they're left over from an old MO install that you partially overwrote. This could be because the installer is broken somehow and only extracted part of the file or something similarly stupid.

If it turns out not to be something to do with this, then I don't know what the issue is, and I'll summon a more important dev who knows what they're doing.

**Comment by KopisGaming** [comment]
Thanks, but I dont know what you mean by hash. When I go under the CRC option, ther is only CRC-32, CRC-64, SHA-1, SHA-256, and an aster-ix.

**Comment by AnyOldName3** [comment]
If the time difference is small, then it's possible that the file times were just copied from the archive, so it's the time those files were compiled rather than when they ended up on your computer.

Regarding the options under CRC, they're different types of hash (well technically, CRC is a checksum, but that's the same thing as far as you need to know). If you pick one, it will apply it to the file in the archive. You'll then remember this (e.g. by taking a screenshot or writing it down or leaving the popup open). The next step is to find the same DLL in your MO plugins directory and hopefully, 7zip will have added a right-click option for CRC/SHA. If you pick the same option as you did for the version in the archive and the sequence it calculates is different, then that means the files are different and you just need to transfer the plugins from the installer to the folder and everything should start working.

**Comment by KopisGaming** [comment]
Some time difference's are small, but others are large. I tried to do what you said and I think they're the same, but I'm not entirely sure. What does that mean? Should I just revert to the old version of MO that I upgraded from?

**Comment by Al12rs** [comment]
The installer on nexus is missing files, use the standalone archive.
And regarding the Mo2 install directory that should be outside the game folder, AnyOldName3 is right, we have been saying and writing this everywhere. Gopher made his guide for Mod Organizer1 not Mod organizer 2. Mo2 is a different program, it is 64 bit and has a coplitely different virtualization library.

**Comment by KopisGaming** [comment]
Then I'll let Gopher know and see what he says. Maybe he'll get around to doing an updated tutorial. And thanks for letting me know about the broken installer.

**Comment by Al12rs** [comment]
About the actual problem I suspect that either windows or your antivirus are bloking them.try right click properties and see if there is the unblock checkbox. If there is it means those are blocked. You needed to download the standalone archive right click unblock that one and extract that one in a folder outside the game. Now it should work

**Comment by Al12rs** [comment]
I wrote about the installer right on the download. Also all this is written in the pinned post on nexus

**Comment by KopisGaming** [comment]
I finished setting up the new MO2 and everything except one thing is working fine. I cant download anything from the Nexus with the "Download with Manager" button.

**Comment by Silarn** [comment]
Run nmxhandler, set it as active, right click on the pane and assign the proper game(s) to the mo exe

**Comment by Silarn** [comment]
There entries higher in the list take precedent

**Comment by KopisGaming** [comment]
Oh! You have to do that on the initial installation too? I thought it was automatically done when you click the "Associate with "Download with Manager" links" button.

**Comment by KopisGaming** [comment]
Ah, yes! It worked. I just needed to register the new installation. Thanks so much for straightening this all out. :)
