### ISSUE TITLE
[Request] Column adjustment

### ISSUE THREAD

**Issue by Nico2b** [ModOrganizer2/modorganizer#325]
# The problem

attached an illustration of the small problem about the Mod name column :

minimize :
![capture](https://user-images.githubusercontent.com/38402724/39089943-32e3013c-45d2-11e8-9b9e-5bd9287b4421.PNG)

then max :
![2](https://user-images.githubusercontent.com/38402724/39089951-629a8058-45d2-11e8-8db1-0accfd953a35.PNG)

after resizing the Mod name column :
![3](https://user-images.githubusercontent.com/38402724/39089963-764b52d0-45d2-11e8-8610-da392d7c5870.PNG)

and re minimize (can't resize the mod name tab, have to maximize the screen before) :
![4](https://user-images.githubusercontent.com/38402724/39089967-8096988a-45d2-11e8-8b96-79f188574673.PNG)

If it's possible to make the Mod name column adaptive if you see what I mean, same for the plugins tab :yum:

**Comment by isanae** [comment]
A column cannot be both stretchable and resizable unless it is the last column. This is limitation of Qt, the user interface library used by Mod Organizer. It is possible to make the name column stretchable so that it receives the additional space when making the list larger, but then it becomes impossible to resize manually.

As for resizing columns that extend past the list, there is a scrollbar at the bottom that can be used to scroll right and readjust the offending columns.
