### ISSUE TITLE
Wont launch Skyrim SE

### ISSUE THREAD

**Issue by Demiaan** [Modorganizer2/modorganizer#337]
# The problem

When I try and launch Skyrim SE with MO2 it starts up with the lock screen on MO2 then just stops and lock screen goes away. I can launch LOOT and SSEEdit just fine in MO2. I can also launch the game normally and with SKSE.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.2
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): 2.1.2
* Desktop OS/version used to run Mod Organizer: Windows 10

# Details

Not sure what happen started the game to test mods and everything was working fine added a few more mods tried to start and it would start.

# Link to Mod Organizer logs

## USVFS

[usvfs-2018-05-03_13-20-52.log](https://github.com/Modorganizer2/modorganizer/files/1971154/usvfs-2018-05-03_13-20-52.log)

## MO Interface

[mo_interface.log](https://github.com/Modorganizer2/modorganizer/files/1971156/mo_interface.log)

**Comment by Al12rs** [comment]
Please try creating a new empty instance (top left button) without any mod (except for skse) and make sure you don't have any dll mods in the data folder or something. If the problem persist then we will need the usvfs logs set to debug level in the Mo2 settings of you reproducing the problem. If it does not happen then it is caused by a mod. You will have to track down what mod is causing this and if is is not a problem with the mod itslef then let us know what mod does not work so we can investigate

**Comment by edst** [comment]
I got the same issue here and wondering why.
here is the log.
https://mega.nz/#!4pEiQTCA!MzHymiBECnUC1yVzYNhIB7D_VCEOf744UPrktMKaveU

**Comment by Al12rs** [comment]
Please test on an empty instance using the latest build available on the discord server

**Comment by Al12rs** [comment]
Will close for lack of response and inability to reproduce in a few days.
