### ISSUE TITLE
SSEEdit and Wrybash save to original plugin folder

### ISSUE THREAD

**Issue by Squirrelydood** [Modorganizer2/modorganizer#351]
# The problem
Both SSEEdit and Wrybash save plugin changes to the original folders the plugins were from. If a plugin overwrites another plugin it saves over the overwriting plugin.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.3 and 2.1.2
* Desktop OS/version used to run Mod Organizer: Win 10 Home. 

# Details

I've used both SSE Edit and Wrybash on plugins in the Data folder, on active plugins run through MO2, and on Active Plugins on MO2 that overwrite plugins in the Data Folder. It saves over the overwriting plugin. I have only one HD on my computer so it's not an issue of the game and virtual folder being on different drives, I also have both saved outside of the programs folder (MO2 is in portable) and the issue still persists. 

This issue only appears to affect Plugins, any other data that is saved is saved in the Overwrite Folder, it is only the plugins that replace existing files.

**Comment by Silarn** [comment]
Only new files are written into overwrite and that's intended behavior. This was changed in 2.1.2 because direct file writes had no easy way to reroute to overwrite and we decided to just unify the whole system.

Most tools offer options to output to a new location now or backup the original file. xEdit does this. I'm not sure if there's such an option for WB.
