### ISSUE TITLE
MO2 (2.1.3) downloads from nexus are 0kb

### ISSUE THREAD

**Issue by Bohauo** [Modorganizer2/modorganizer#356]
I may have posted my issue on the wrong place, anyhow here is the link to the my problem:

https://github.com/TanninOne/modorganizer/issues/1180

**Comment by keem85** [comment]
Same here! I have the same issue!

**Comment by keem85** [comment]
AnyOldName3 from Discord helped me out. Go to nexus tab on the settings, and set CDN as preferred download handler (dragndrop)

**Comment by Silarn** [comment]
There are issues with certain Nexus servers they they haven't yet resolved since disabling HTTP and the old nmm.nexusmods.com subdomain. Using the CDN as your preferred server is usually the best idea.

However, I do note that this seems to be indicating legacy-api now so there may still be an issue with this server I'll have to bring up with the Nexus team.

**Comment by Bohauo** [comment]
Ok, so it seams like a good workaround for now...
please report back once fixed...

**Comment by Al12rs** [comment]
It's not on our end, its a problem with the Nexus EU#1 and other servers still using the wrong api name
