### ISSUE TITLE
Installing the same mod while the first installation is still completing crashes Mo2

### ISSUE THREAD

**Issue by Al12rs** [ModOrganizer2/modorganizer#367]
# The problem

not much to say other than the title. Might need something that takes enough time to install to give you the chance to start the second one.

# Environment

* Mod Organizer Version that exhibits the issue:2.1.3
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:

**Comment by GioGr** [comment]
was gonna report this also

when installing big mods and by mistake u go to MO again but not the installing window that has not locked the main window(thats the bug(but should still let downloads through as it does now))
and u activate same or different mod to install it crashes

also while the downloads show progress at window taskbar, the installations do not

**Comment by dartigen** [comment]
I've had the same happen, with installing two different mods - one was still copying files. The main window doesn't lock during installs, which I think is part of how this crash can happen.

Ideally, MO should only allow you to install _one_ mod at a time, and should either lock the main window or otherwise make the user wait until all files have finished copying from the previous mod installation before allowing any further installations to happen.

**Comment by Al12rs** [comment]
merging into #300 for organization
