### ISSUE TITLE
How do I completely remove you from my computer

### ISSUE THREAD

**Issue by Lady3vil** [Modorganizer2/modorganizer#419]
# The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Mod Organizer). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to our disco button channel
MOD2  can not perform one simple function

# Environment:  Nexus Mod, Your Program, Fallout 4

* Mod Organizer Version that exhibits the issue: V 2.3
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): same version
* Desktop OS/version used to run Mod Organizer: Windows 10 compatible with WIndows  8

# Details: All my files that MOD2 pulled from Nexus Mod Manager, are named Unmanaged, when I click on MOD2 to launch Nexus Mods online, it takes the file and has a list of reasons why I cant find the file anywhere in the game, like and cant find what back end file did you hide your uninstall info, so I can remove you. I thinking Ive removed you from everywhere, I go online to Nexus to download and MOd2 hacks it. 

If necessary, describe the problem you have been experiencing in more detail. See Above...

# Link to Mod Organizer logs: 

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs! And here's what I propose, lets revert to the title of my issue. How do I completely remove you from my computer?!

**Comment by Al12rs** [comment]
Go in appdata/local/ and delete the modorganizer folder. After that you need to go in the Nexus Mod Manager settings and select associate with Nexus links or something like that.

**Comment by Silarn** [comment]
I mean, MO2 is easily uninstalled by simply deleting it. It doesn't create registry entries. At most nxmhandler might 'claim' NXM links, just like NMM does (as Al stated).

Beyond that, while it will not affect your game if you aren't using MO2, if you created an instance you may want to go to your Local AppData directory and delete the ModOrganizer and usvfs directories. (Assuming you did not manually change the location of your MO2 instance files, in which case you should know where you moved them to.)

Anyway, is sounds like you didn't really bother to learn how MO works, and I can't really understand what problem you were having before. MO2 is intended to be run with a clean game directory, and having 'Unmanaged' mods generally means you left a bunch of other mods in your game directory from a previous mod manager install. You will have to clean those up yourself since MO2 has nothing to do with those files.
