### ISSUE TITLE
Can not Unlock plugins - no Lock icons present either.  I am using MO2 version 2.1.3, on Windows 10.

### ISSUE THREAD

**Issue by MorbidBoyd** [Modorganizer2/modorganizer#442]
# The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Mod Organizer). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to our discord channel

# Environment

* Mod Organizer Version that exhibits the issue:
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:

# Details

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by LostDragonist** [comment]
If you don't see any lock icons in the plugin flags column, then there are no locked plugins.  MO 2.1.3 does have a bug that prevents locking plugins but that shouldn't affect you as you want them unlocked.

**Comment by MorbidBoyd** [comment]
The plugins don't move from their positions, and this occurred after I selected a group (for Perkus Maximus) and selected Lock.  When I try to drag and drop, they immediately bounce back into their old position.  Is there a way to allow me to move these?  Drag and drop worked fine before.

 

Thank you for your  time and help.

**Comment by LostDragonist** [comment]
You can check out lockedorder.txt in your MO2 profile to confirm that nothing is locked.  Other than a locked plugin order, there are two main things that will prevent you from moving plugins.  

First, masters will always be above non-masters.  You can identify masters by a bold typeface.

Second, sorting by anything other than priority.  MO2 just won't let you move anything otherwise.  If you're not sorting your plugins by priority, click the priority column header.

If that doesn't do it, please provide more information like your actual load order.  A screenshot would be fantastic.

**Comment by Al12rs** [comment]
I would ask you to please just try the latest Dev build from the Mo2 discord server linked at the top of the GitHub page. We fixed issues there and that will make it easier to understand what is already fixed and what isn't.
