### ISSUE TITLE
[USVFS] OBSE Steam version can't be launched and hooked from MO2

### ISSUE THREAD

**Issue by PrivateUnknown** [ModOrganizer2/modorganizer#447]
# The problem

The Script Extender workaround for Oblivion will not get loaded by OBSE when launching through Steam. 
obse.log displays the following:

plugin E:\Steam\steamapps\common\Oblivion\Data\OBSE\Plugins\\usvfs_x86.dll does not appear to be an OBSE plugin

However hook.dll from MO1.3.5 will get loaded by OBSE and does work correctly with MO2.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.3
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): 1.3.5
* Desktop OS/version used to run Mod Organizer: Windows 10

**Comment by Al12rs** [comment]
The script extender workaround is not available with the new VFS library, to fix this issue usvfs should hook createRemoteTread and initialize usvfs on that thread as well if it wasn't initialized already in the main thread. This way OBSE will not bypass the usvfs initialization that happens on the main thread because it's still suspended when he new thread is launched.
This is not an easy change so help wanted on this one.
