### ISSUE TITLE
MO setting creation club files as overwrite

### ISSUE THREAD

**Issue by Abydos2** [Modorganizer2/modorganizer#456]
# The problem

Mod Organizer flagging Creation Club downloaded files as overwrite files.

# Environment

It happened with the latest version 2.1.3

# Details

This is an example of what had happened. I saw that they had introduced a new thing on creation club, allowing a companion that follows you around with a self-aware AI power armor suit that you can install in any power armor. So I decided to get it.

However because I had Mod Organizer installed, when Fallout / CC tried to download and install the 'mod', Mod Organizer flagged the files as "Overwrite" files and wouldn't allow it to be installed. I had to uninstall mod organizer, download the files and then reinstall mod organizer to get it to work.

**Comment by Al12rs** [comment]
That is just expected behavior. If a program (in this case FO4) creates new files (in this case the CC mod) those get put in the overwrite folder instead of the game folder. This way you leave the game folder completely vanilla. Now once you have closed the game you can right-click on the modlist->all mods-create empty mod and name it CCModWhatever, and now double click on overwrite and drag and drop the files in there to the new CCModWhatever. Make sure the plugins are activated in the right pane and you are done. 

You want CC mods to be installed in the game folder and not in MO2? Then run the game from outside Mo2, install the CC mods, close the game, open MO2, make sure the CC mod plugins are activated and run the game from there.

No need to uninstall anything. What you described was completely expected behavior.
