### ISSUE TITLE
Disk full marks downloads as successfully completed.

### ISSUE THREAD

**Issue by AnyOldName3** [Modorganizer2/modorganizer#470]
# The problem

If a MO download fills up a disk drive, instead of giving an error message to say that there's no space to finish the download, it's marked as completed.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.4 release
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): Not tested
* Desktop OS/version used to run Mod Organizer: Windows 10 

# Details

N/A

# Link to Mod Organizer logs

## USVFS
N/A

## MO Interface
I accidentally overwrote the log by opening MO to double check if it was up to date. I've since cleared up some disk space, so can't easily regenerate it. Hopefully, the issue is simple enough that this is completely irrelevant.

**Comment by LostDragonist** [comment]
Commit 67287048dd7ae276b916861d948701c649d88a5e looks for error when writing downloads to the storage drive.  It will inform the user of the error, suggest looking at the available space, and cancel the download.  

I spent a good amount of time trying to leave the download in a state where the user could resume it without (1) corrupting the download and (2) deadlocking MO2.  The deadlocks appeared to be due to MO2 trying to open the download's metafile multiple times.

The main issue of leaving a corrupt download in a ready state is fixed so I'm closing this issue.
