### ISSUE TITLE
Upgraded to Win10, MO2 no longer virtualizes[FIXED, not solved]

### ISSUE THREAD

**Issue by SuwinTzi** [ModOrganizer2/modorganizer#543]
FIXED:
I guess I was missing something else cause after I ran CS:GO through Steam, Steam installed some requirements for CSGO and now I'm seeing my mods/saves in-game.  I don't know what was missing, cause I had uninstalled and reinstalled MO2 using the archive.

Upgraded to Win10 from Win7x64 and after reinstalling MO2 due to a missing .dll, MO2 no longer setting up virtualization for SkyrimLE properly

Environment: Win10 and latest MO2 from Nexus

Steps:
When upgrading, selected to keep user prefs
Upgraded successfully
Ran OSSUWin10 to disable some tracking behaviours (only recommended ones)
Attempted to start MO2
Received error notification (mentioned missing files, might've been VS?  Can't remember). Error recommended reinstalling MO2.
Redownloaded installer version from Nexus and reinstalled succesfully.
Used "Instance Selection" option to relocate my profiles in AppData
MO2 displays installed mods, both left and right panes correctly.
Executables other than CK, SKSE and Skyrimlauncher missing from drop down menu.
Run SKSE.
Skyrim does not show save games, nor any modded UI, text, etc.  New game does not go into AltStart and does Vanilla intro.

Logs:
The logs are empty.  All of them.

Was there something I'm supposed to ensure is disabled or re-enable?  Am I missing something else?  MO2 definitely still sees everything outside the game properly, but the game isn't being "called".

MO2 and the MO folder in AppData is on WinDef exclusion lists.

**Comment by SuperSandro2000** [comment]
If you can't remember the missing files then take a look again. Maybe windows removed a vsc++ package?

**Comment by SuwinTzi** [comment]
I didn't get the error message after reinstalling, which isn't the current issue.  The current issue is that MO2 isn't running the mods in the game.

I'm getting a completely vanilla Skyrim, despite my left and right pane showing my installed and activated mods/esps.  It's what I wrote in the steps I took.

**Comment by SuperSandro2000** [comment]
![](http://i.bittwiddlers.org/LIt.png)

**Comment by SuwinTzi** [comment]
@SuperSandro2000 the usvfs are empty.  There's nothing in them.  You want me to post blank logs?

**Comment by Project579** [comment]
If the usvfs logs are blank (0kb) it can mean two things: 
1) The windows Event Logs are not working correctly, this can happen if the Event service was stopped or if the Event Logs have been cleaned with CCleaner or by some other mean. 
To fix this case you should reboot your PC (with reboot I mean using the restart option, not shut down, that will not do anything since windows just saves the current state for faster startup) and make sure to complete any pending Windows Updates as those can often compromise Windows's normal behaviour untill they are finished installing.
2) Usvfs is being blocked by either Windows or your Antivirus. You can check if windows is blocking the usvfs files by right clicking on them, properties, general and see if there is a checkbox to unblock them: https://cdn.discordapp.com/attachments/458597400638914563/458726709748039682/unknown.png .
You should then go check if your Antivirus (windows Defender can be an offender too) is blocking the usvfs files and make sure that isn't the case by temporarly disabling it and reinstalling Mo2 while it is disabled to avoid any files getting deleted.

**Comment by Project579** [comment]
You can join the discord for fast support in case you want to.

**Comment by SuwinTzi** [comment]
@Project579 Event service shouldn't be stopped.  Right before attempting to start SKSE from MO2, I restarted due to updating Nvidia drivers.  After the first time it failed to load mods, I restarted again.  The logs from all times I've attempted to run the game are empty.

2nd condition doesn't apply either, the logs are lacking the checkbox, and as stated, MO2 was one of the first things I added to the exclusion list.

Gonna try redoing the directories, found a similar issue online.

**Comment by Project579** [comment]
Make sure your windows does not have any updates available, also check you antivirus.

**Comment by SuwinTzi** [comment]
@Project579 Uninstalled, reinstalled, logs still empty, no pending updates, antivirus is only WinDef, I added all associated apps to MO2 and TESV to exceptions and process overrides.  Still not working.

Still vanilla Skyrim

**Comment by SuwinTzi** [comment]
@Project579 OKAY SO apparently was missing something, cause I ran CS:GO, Steam did some "first time installation" window, after a round, tried launching MO again, and now it works.
