### ISSUE TITLE
[Feature Request] Additional tracked Flags

### ISSUE THREAD

**Issue by DJGoo** [ModOrganizer2/modorganizer#556]
# The problem

The current update system built into mod organizer 2 isn't very reliable thanks to the varied and unpredictable versioning schemes mod developers use on the Nexus. I find the nexus's tracking centre much more reliable since it relies on the last upload vs my last download. So it would be beneficial to add flags to indicate if I have tracked the mods I have installed or not, similar to the flags for endorsements.

# Environment

* Mod Organizer 2 on Windows 10

**Comment by Project579** [comment]
I'm not sure if the API actually allow access to that information.

**Comment by Silarn** [comment]
With the new API there are likely going to be a number of possible update states. The file itself can be flagged as having an update. The mod version could be changed. There could be a new file uploaded. If we're going to implement checks for these various indicators then it might be good to refine the filter so we can see clearly what definitely has an update, might have an update, seems to be mismatched, or has a newer file available that isn't necessarily an update.

**Comment by LostDragonist** [comment]
https://github.com/ModOrganizer2/modorganizer/commit/d5332c5080ea5e1d0812cc900bb5ed6e20ff8f0e adds support for retrieving the tracked status of mods and displaying it.  Tracked mods will have a red pushpin present in the mod list flags column.  The state of the tracking can be set by right-clicking the mod and selecting "start tracking" or "stop tracking".

Due to the way the API for this is implemented, the only times the tracking status will be updated is if the user tries to set the tracking status or if the user does a global update check from the small tools menu.

**Comment by Al12rs** [comment]
2.2.0 released on nexus
