### ISSUE TITLE
Bad download behavior

### ISSUE THREAD

**Issue by EssGeeEich** [ModOrganizer2/modorganizer#575]
# The problem

Buggy download behavior.

# Environment

* Mod Organizer v2.1.5
* Desktop OS/version used to run Mod Organizer: W10x64 latest update.

# Details

Double-clicking a download that's in progress always causes an application hang, and sometimes a full crash.
The columns don't represent the table contents at all.
When a download is in a "unknown" state, it cannot be canceled or removed, when in reality every download item should be removable.
This causes another issue: If a download freezes in that state, you have to restart MO in order to be able to restart it, because it cannot be canceled nor removed anymore and the file is locked, preventing a new download from starting.

# Link to Mod Organizer logs

The logs don't tell much about those issues, but I'll be happy to provide them if that helps.

**Comment by Al12rs** [comment]
Could you test the 2.1.6 Dev builds i think I did fix some of those hanging problems there. 
The downloads tab is pretty buggy though and would really need to be rewritten.
First though we need to wait for nexus to release their new API or we risk having to rewrite stuff twice.

**Comment by EssGeeEich** [comment]
I can't seem to find any 2.1.6 dev build nor any related commit...
Anyways, about the nexus api, have you already seen this?

https://github.com/Nexus-Mods/node-nexus-api/tree/master/samples

**Comment by Al12rs** [comment]
The device builds are on discord here: https://discord.gg/MB3CyMH
We are in contact with the nexus guys and they asked us to wait until they release their finished version of the API before we use them. We will have a three month period to make the transaction before they will then remove the old ones.
Silarn has already made some changes based on the version Vortex uses so that when the third party version is out it will be faster.

**Comment by Al12rs** [comment]
I can't reproduce these issues after the recent fixes to downloads, will close for now. Might reopen if the issue comes up again.
