### ISSUE TITLE
Wrye Bash and MO2

### ISSUE THREAD

**Issue by Strategun** [ModOrganizer2/modorganizer#577]
I cannot create a bashed patch with Wrye Bash with MO2. When it supposedly finishes creating the bashed patch, it freezes eternally and gets stuck and I have to manually kill Wrye Bash.

I am using:
Mod Organizer 2.1.5
Win7 64 Bit
WryeSmash 307.201807040057

I do not know how to work around this, because if I use Wrye Bash without MO2, it will only find the four default files, without any mods, so I don't really have any way to created a bashed patch. I upgraded from NMM to MO2 after a fresh install and now I came up with this problem.

**Comment by Al12rs** [comment]
Could you try creating an empty `docs` folder inside the Overwrite folder before running WB? 
We are investigating a similar issue and if that works there is a good chance they are the same problem.

**Comment by Strategun** [comment]
Hello there, thanks for the quick reply. I guess I won't be able to comply with your request since I actually managed to get Wrye Bash to work another way, since it was a fresh install, I ran Wrye Bash normally/independently (outside of MO2), and created a bashed patch without any mods, since mods aren't detected outside of MO2. The bashed patch was created successfully and then I tried once more to create a bashed patch, this time through MO2 with all the mods enabled and it worked. Hopefully it can bring some insight to you, and if there is any more way I can help, I'd be glad to. Don't hesitate to ask.

**Comment by Al12rs** [comment]
We released a test version of usvfs on discord: https://discord.gg/ucVRQPV . It aims to fix an issue on BodySlide and we ware hopeful it could fix the WB issues as well. If you could try it out it could be helpful.
The reason your workaround worked is because that way you ended up generating the docs folder in data which is what seems to make the issue go away.
I also was able to explain why the docs folder was needed in data at some point but it was some time ago. I will revisit the WB issue after we are confident that the Bodyslide issue fix is good and does not cause other issues. For that we need more testing.

**Comment by Al12rs** [comment]
This is same as #506

**Comment by Al12rs** [comment]
This should have been fixed in 2.2.0, or possibly with recent usvfs patches on disocrd if that is not the case.
Could you please test if the issue is resolved? 
If no response within 20 days we will assume the issue resolved.
