### ISSUE TITLE
MO2 refuses to load Skyrim SE from steam. 

### ISSUE THREAD

**Issue by TheAngryD** [ModOrganizer2/modorganizer#587]
# The problem

All mods correctly installed. MO2 starts loading process and then nothing. Cannot run Skyrim from within the MO2 at all. 

I'm not posting logs because other users have and you basically ignored their questions. Either fix it or don't, but you wasted my entire afternoon with this nonsense. I'll use another mod loader. Thanks for nothing.

**Comment by TheAngryD** [comment]
Wow, what an absolutely useless comment to make. There are thirteen different reports of this bug already in the system. Each of them was closed by a developer without resolution. Why waste the time adding details when the devs are just going to ignore it? This is a known issue with the first report in May of this year. If it's not important to the devs, it isn't important to me. 

Vortex is working just fine.

**Comment by Al12rs** [comment]
@TheAngryD The behaviour you are describing is simply the game crashing on launch, which is usually caused by either outdated mods or incorrect INI settings.
There is nothing indicating this is a Mo2 issue, and not simply some mods issue.

There are also many ways to test this, for example: does the game launch correctly on a new empty Mo2 profile? If yes then it's a mod or INI change that causes the crash.

If it still didn't work then that probably means there is an incorrect setup of Mo2, such as a wrong path to the game etc.
In this case supplying the logs would help us identifying such issues.

Without this kind of information you are frankly waisting people's time.

We are simple users just like you that decided to try making the an open source program work and add features to it. If something is not working then you try to help us fix it, you don't demand it to be fixed.

I would ask you to make the test I described above but I see you have moved to Vortex and that makes me sad (for the Vortex developers that need to support people like you).

**Comment by TheAngryD** [comment]
Weird how Vortex, with the exact same mods, ran flawlessly. That’s the only test I need to be making, thanks. We’re done here.
