### ISSUE TITLE
FNIS pulls animation files that aren't loaded, perhaps from a different profile.

### ISSUE THREAD

**Issue by Abdul-wahad** [ModOrganizer2/modorganizer#602]
# The problem

When only the base and DLC esm's are loaded and FNIS is run from within MO2, it compiles files from animation mods that are not checked.

# Environment

* Mod Organizer Version 2.1.6 rev e2b799b
* Last Mod Organizer Verizon that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: Windows 7 SP1

# Details

If I run FNIS with only the base and DLC esm's checked on the right side, and no other mods show on the right, either checked or unchecked, FNIS runs and starts to use mods that were used in different profiles.  I load up a new version of MO occasionally and install, but don't enable, my preferred mods and add-ins, then make a new profile.  That new profile is used to enable some mods, run FNIS, then start SKSE to see if it loads or CTD's.  I would have thought that FNIS would use only the mods that were enabled in the currently running profile.  The default and DLC esm's are in the data folder of Skyim (not in program files) and show as unmanged, so no mods are checked on the left side at all. 

# Link to Mod Organizer logs

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by Al12rs** [comment]
I think you are misinterpreting what disabling a plugin does. Not all mods come with plugins, the game does not load only plugins, it also loads textures and meshes and animation files etc. A plugin is a special file that tells the game to change things in like adding quests, changing values of weapons and many more things, even loading custom textures and assets that the game would not load otherwise. But disabling a plugin does not mean that the game will not load the other files from the same mod.

If you want to disable a mod so that the game does not see it you need to disable it from the left pane, that way neither the plugins nor the other assets are loaded. Usually you should not disable plugins and expect the mod to be entirely disabled. Like I pointed out before there are many mods that don't even require a plugin to work, the game just loads those assets .

**Comment by Abdul-wahad** [comment]
There are no mods checked on the left side.  For some reason, FNIS through MO seems to be executing from a different installation point, and not from the currently loaded profile.  I never used the term plugin.

From my first post:

The default and DLC esm's are in the data folder of Skyim (not in program files) and show as unmanged, so no mods are checked on the left side at all.
