### ISSUE TITLE
Fallout 3 - Strange error when installing an archive

### ISSUE THREAD

**Issue by Yoplala** [ModOrganizer2/modorganizer#612]
# The problem

I'm trying to install this mod for Fo3: https://www.nexusmods.com/fallout3/mods/20035.
He has an installer I don't know and at the installation with MO2, I have this message.

![capture](https://user-images.githubusercontent.com/36462558/50636667-45da0c00-0f57-11e9-8151-e76d73bec3ad.PNG)

The installation is going well anyway, everything seems to be there. It is actually an empty xml, but useful mod from what I understand. A MO2 error or this kind of installer?

On Discord, LostDragonist advised me to come here because it could be a MO2 problem. 

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.6 and 2.1.7
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Windows 8

**Comment by LostDragonist** [comment]
I took a quick look at this when first reported.  The installer is a C# script.  The problem appears to be that the installer first tries to install includes_HUDMainMenu.xml and then tries to edit the file it just installed.  This error occurs as it can't find or access the file (probably access given the error).

**Comment by ewillett804** [comment]
If this is still occurring please provide the MO2 debug log.  if the game is installed on drive C in the user's directory it is possible that access-issues from windows is preventing the scripted edits.  Otherwise we should be able to close this within 20 days if no new information.

**Comment by Syer10** [comment]
Decided to test since I have a TTW instance. It still happens on the latest MO2 beta(2.2.2alpha5) This seems to only happen on my empty profile. Its probably because the file doesn't exist on my empty profile, so it installs it and tries to edit it, instead of editing the one already there. 

Game Directory = D:\Games\SteamLibrary\steamapps\common\Fallout New Vegas
MO2 Directory = D:\Game Related\Mod Organizer 2
TTW Instance Directory = D:\Game Related\Tale of Two Wastelands\Mod Orginizer 2

I will attach my debug mo_interface.log
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/3752542/mo_interface.log)

**Comment by Holt59** [comment]
This should be fixed in the next MO2 release with the "built-in" installer for FOMOD C# archive. 

This PR fixes the actual problem when installers try to edit files that have been extracted or generated https://github.com/ModOrganizer2/modorganizer-installer_fomod_csharp/pull/1
