### ISSUE TITLE
USVFS Error

### ISSUE THREAD

**Issue by Elscrux** [ModOrganizer2/modorganizer#634]
# The problem

When I try to start any application in MO2 I get an usvfs error

# Environment
Both MO2 v.2.1.6 and v2.1.7alpha3 don't work(It did work perfectly fine before, but since yesterday it does not)
Windows 10 64bit

# Details

I get the error Unhandled USVFS proxy exception (line 110)
I get the same error when I start usvfs_proxy_x64.exe

I tried restarting and deleting the AppData\Local files

# Link to Mod Organizer logs

## USVFS
The USVFS log is empty

## MO Interface
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/2792525/mo_interface.log)

**Comment by LostDragonist** [comment]
That error indicates some sort of issue is preventing USVFS from creating a file in C:\ProgramData\USVFS.  

Things to try:
* Restart your PC.
* Disable anti-virus programs.
* Create C:\ProgramData\USVFS if it doesn't exist.
* Delete C:\ProgramData\USVFS if it does exist.

**Comment by atrHusK** [comment]
I hope you can forgive me on bumping this bug. I've been experiencing the exact same thing and this pointed me into the right direction but I also believe the true cause is actually unresolved. Since a non experienced user will have likely have trouble fixing it I think an enhancement might be a good idea here.
The cause is that the first user that uses MO2 holds the rights to C:\ProgramData\USVFS which causes other users of the same computer to get this error. You can read a bit about the situation here: https://stackoverflow.com/questions/22107812/privileges-owner-issue-when-writing-in-c-programdata

Perhaps it would be better to build the USVFS inside the localappdata directory? You could also make a per user USVFS directory if you feel localappdata is not appropriate here.

Anyway, thanks for pointing me into the right direction. 
For tech savvy users: A workarround other than running as admin (which you should really try to avoid, always) is to change the security settings (ACL) on the C:\ProgramData\USVFS to allow other users modify rights on it.
