### ISSUE TITLE
SKSE Won't work with SKSE

### ISSUE THREAD

**Issue by StarDuelist** [ModOrganizer2/modorganizer#635]
When I run Skyrim through it's regular launcher on MO2, it works perfectly. But if I run it through SKSE on MO2 and try to load the save, it says the save is missing files and then crashes, even though MO2 doesn't say I am missing any plugins. And if I try to start a new save, it just leaves me on the main menu without any ui. I have SKSE installed properly and it works fine when I launch it by itself.

**Comment by Al12rs** [comment]
This usually means that either one of your mods or INI files is causing a crash, to try to confirm this you can try reproducing the issue on a new empty profile:

To check whether the issue is related to one of the mods installed or your ini settings, see if it keeps happening in a new empty profile:
https://cdn.discordapp.com/attachments/403979692501106688/524939782435110924/unknown.png
https://cdn.discordapp.com/attachments/403979692501106688/524940397643038740/unknown.png

Also make sure you don't have any mods installed in actual game folder, and test if the issue happens outside of Mo2 if you didn't already.

Let me know if this solves the issue. If it doesn't you might want to consider joining the discord server and discuss the issue there instead: https://discord.gg/6GKR9jZ

**Comment by StarDuelist** [comment]
It seems like I’m missing some plugins in my Skyrim ini files. I don’t know
what I’m missing specifically. Could you show me what my Skyrim and
skyrimprefs  should look like? The verify cache option on Steam doesn’t
seem to change it.

**Comment by Al12rs** [comment]
I'm sorry, but I don't actually play the game anymore. Since this does not appear to be a Mo2 issue and I can't provide more help I'm closing this. You might have more luck on either Reddit or discord.

**Comment by StarDuelist** [comment]
I understand. Thanks anyways.
