### ISSUE TITLE
Upgrade Nexus mod update check to new API

### ISSUE THREAD

**Issue by Al12rs** [ModOrganizer2/modorganizer#637]
Task:
Implement checking if a mod file received a direct update.
If that is not the case but the mod has a new overall version check if the file was moved to Old files or Deleted, in that case we can safely assume there is an update for that file.

There are other cases and states to analyze depending on the capability of the new api.

**Comment by cibrhusk** [comment]
I've been using stable and have since updated to the latest 2.2.0-beta8 using nexus api and the following issue exists in both versions, I think however this issue is linked to how you would want to fix it.
**The problem:**
While modding Morrowind I've noticed more than a few mod authors forget have a mod page with a lower version number than the main file (or other files at that). See for example https://www.nexusmods.com/morrowind/mods/45972

If you download+install from such a mod page then Mod Organizer keeps thinking an update is available, it installs the file with the correct version number for the file itself, but the update check apparently does not check the file version but only the mod page version, which is usually lower.

If this is difficult to implement, then perhaps you can add an alternative mechanism that just checks if the mod page was modified since the last ignore of an mod update.
