### ISSUE TITLE
Skyrim Nexus no Download with Mod Manager button. Went through tutorial 8x.

### ISSUE THREAD

**Issue by Darklustre** [ModOrganizer2/modorganizer#645]
I just started a new instance to begin using this with Skyrim. However I can't get Nexus to recognize MM and give me the Download with Mod Manager button. I've gone through the steps on the tutorial 8x and use the button to open Nexus to find a mod to download to continue to the tutorial. After trying to install 3 mods, (one of them Frostfall, which is really popular), I still can't get anything more than a manual download. 

Your help is appreciated.

**Comment by Al12rs** [comment]
For this kind of issues it's better to ask on discord since there you are more likely to get faster help. 
Basically tutorials have not been maintained for a long time so there is the distinct possibility they are broken. If you can just skip the tutorial and try downloading a mod after you made sure that you have successfully logged in your nexus account from mo2. 

We are actually working on a new version of mo2 that uses a new authentication system without the need of logging from MO2. That is also available from discord:
https://discord.gg/6GKR9jZ

I'm closing this issue for organization but please reopen it if need be.
