### ISSUE TITLE
Downloads freeze Mod Organizer (downloads folder on network drive)

### ISSUE THREAD

**Issue by bliblablob** [ModOrganizer2/modorganizer#660]
## The problem:
Starting/Finishing a download of a mod or installing a mod freezes the interface of MO2 completely for a few seconds up to half a minute. The problem seems to be caused by my setup: my downloads folder is stored on a network drive (although with a pretty fast connection). However, each time MO2 "does something" inside in the downloads folder (I guess updating its meta files) the complete interface will freeze until MO2 is finished. The problem is absent when locally attaching the drive (or at least much less severe).

My suggestion would be to make the downloads part of MO asynchronous or not blocking the rest of the interface if that is possible.
## To Reproduce:

Select a network drive as your download location & download and install mods. 

## Environment:

* Mod Organizer Version that exhibits the issue: 2.2.0beta2 as well as 2.1.6
* Desktop OS/version used to run Mod Organizer: Windows 10

**Comment by bliblablob** [comment]
As a small addendum:
Using the newest beta (2.2.0beta3) the problem still persists. Additionally startup can now take several minutes with my downloads folder on a network share. Also, if you start downloads during that frozen state MO will often miss them.

**Comment by Al12rs** [comment]
The extremely high latency sounds like spin up time of the remote drive, but from what you described it seems unlikely. 
Since this is a very specific case with the remote drive and all I can't give it much priority, but we do know of the performance issues of the downloads tab, and I mean to address them in the future once other features have been fixed and released.
For now it works good enough for most users so I'm afraid this can't be of high priority.
(if you want to know what we are currently up to you can look [here](https://github.com/ModOrganizer2/modorganizer/projects) and [here](https://github.com/orgs/ModOrganizer2/projects) .

**Comment by bliblablob** [comment]
It's probably not the spin up time as I use this network share on my machine for many more applications and it works just as if it were a local drive (read/write speed are ~15 MB/s, so slower than local but also not too shabby). 
To me is seems that each time only a single download finishes/starts/is installed MO "syncs/refreshes" the whole download directory, when it would probably be enough to only sync the meta file of this one mod. Which in turn leads to the problem that the whole interface has to wait for the downloads tab to finish its refresh.

But anyway, I do agree you have more important stuff on your plate and I appreciate you taking the time to answer.

**Comment by Al12rs** [comment]
Closing this since it's just a matter of improving downloads tab performance and that is already on our radar.
