### ISSUE TITLE
Unable to start Bodyslide 64

### ISSUE THREAD

**Issue by Lifferds** [ModOrganizer2/modorganizer#668]
## The problem:
When I try to start BS64 the vfs initializes, locks and unlocks w/o BS starting. I have checked paths and they are identical to Outfit Studio except for file name (Outfit Studio starts fine).

## To Reproduce:
Bring up BodySlide x64 and click Run.
Log says "Waiting for process completion not successful: 258"

## Environment:
* Mod Organizer Version 2.1.6
* 2.1.6 At one point MO2 blew itself up and executables were gone. Unpacked it w/o overwriting old files because I didn't want to lose my work. After that the problem began.
* Win 10

## Details:
I have reinstalled BS several times from MO2 with Merge so I wouldn't destroy work.

## Link to Mod Organizer logs:
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder". You should close MO2 before sending or examining the logs as they are finished writing only after the program is closed.

### USVFS:
https://gist.github.com/Lifferds/bfbba556ca1e48926efc71250c67bfcf

### MO Interface:
https://gist.github.com/Lifferds/020905227bd682b1756e197e726f05b7

**Comment by Al12rs** [comment]
You need to overwrite when installing Mo2 files, you will not break the mods. You will simply overwrite the executables and binaries of Mo2. If there is a problem with 2.1.6 you can go back by overwriting again.

Otherwise you can use the installer, point it at your existing Mo2 install path and let it update Mo2 for you.

After you have made sure the update was successful, try deleting the executable entry for BodySlide and creating it again from the data tab in the right pane.

**Comment by Al12rs** [comment]
Closing this for organization purposes, please reopen if you still have this issue.
