### ISSUE TITLE
Extended Dialogue Interface BUG

### ISSUE THREAD

**Issue by SiTWulf** [ModOrganizer2/modorganizer#682]
## The problem:
Extended Dialogue Interface not work with MO2.
The Mod only works if you put the file XDI.ESM into Overwrite folder

## To Reproduce:

1. Go to https://www.nexusmods.com/fallout4/mods/27216 and Download MOD
2. Run the game and check... you not have a working XDI.

## Environment:

* Mod Organizer Version that exhibits the issue: All (2.2Beta8)
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Mod Organizer: Windows 10

## Details:
Is really strange, only the game cant see the file, but MO2 can see the file, and if you use the "Explore Virtual Folder" can see the file too.

XDI.ESM appear in Plugins List (Activated) and in Mod List "Extended Dialogue Interface 1.3.3) (Activated), shows in Data Tab, but the game not show it...

**Comment by LostDragonist** [comment]
What version of MO2 are you using?  This should have been fixed with 2.1.6 though it would require you to reinstall XDI.

The fundamental issue is a bug with the games where they will straight up ignore files with certain file attributes.  Before 2.1.6, MO2 was improperly extracting XDI which would lead to abnormal file attributes.  This part has been fixed.  There's not much we can (or are willing to do) about the games.

The 2.2.0 betas have a file attribute checker than you can enable that will check for these abnormal attributes and attempt to fix them.

**Comment by LostDragonist** [comment]
It's also worth noting that the file attributes that affect this are designed to change over time.  A file that worked when first installed may end up not working later on.  This is because the file attribute is normally used by some sort of backup software to determine which files have already been backed up.

**Comment by SiTWulf** [comment]
Actually running v2.2Beta8 with activated the option: "Enable Parsing of Archives (Experimental Features)"

**Comment by Qudix** [comment]
You need to reinstall XDI

**Comment by SiTWulf** [comment]
Reinstalled and the error persists...

**Comment by LostDragonist** [comment]
v2.2.0beta8 has no issues install XDI.  Sort of.  Nothing we can really help, at least.

The files extract without the ARCHIVE flag.  That means that *any* other flag your PC puts on the file (read-only, system, hidden, not content indexed, sparse, compressed, etc. etc.) will make the file invisible to the game.  You can usually see the offending attribute by going to the mod folder, opening a powershell, and entering the command `attrib .\XDI.esm`.  In my case, it has exactly 0 attributes so the game can see it.

The reason moving the file to overwrite works is because any file modified, moved, copied, etc., gets the ARCHIVE flag attached to it so that backup software knows to back up that file.  

Hopefully something in there helps.  Check out the file attribute checker.  Settings > Plugins > Basic diagnosis plugin > check_fileattributes = true.  It can take a while to run at first but will help prevent issues like this.

Closing this issue as it's already been fixed and there's nothing further we can do about it.
