### ISSUE TITLE
Can't get version for Fallout 4 mod when installed manually

### ISSUE THREAD

**Issue by Tj3n** [ModOrganizer2/modorganizer#711]
## The problem:
Can't get version for Fallout 4 mod when installed manually, but download with MO2 and install then version show correctly, it worked again if using the `Check for updates` feature.

## To Reproduce:

1. Install a mod manually
2. Add mod's ID
3. Go to Nexus info tab, source game is Fallout 4
4. Info fetched but version is empty, nothing unusual in log

## Environment:

* Mod Organizer Version that exhibits the issue: 2.2.0
* Last Mod Organizer Version that did not exhibit the issue (if applicable): Probably older version don't have
* Desktop OS/version used to run Mod Organizer: Windows 10

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

### USVFS:
https://gist.github.com/Tj3n/1a555dce9a211f6ec1d78b9627f6c76a

### MO Interface:
https://gist.github.com/Tj3n/cf0f332f0fa17203c6a3864786373935

**Comment by Al12rs** [comment]
This is expected behavior and it won't change. You need to perform a check for updates to actually get correct file version info. The nexus tab is populated using an API endpoint that does not return file version information. To avoid unnecessary use of api calls automatic version information retrival upon opening the nexus tab will not be implemented. 
Now you should have a Force Check for Update context menu option on the mod that should do exactly what you need after setting the id.
