### ISSUE TITLE
Feature request: Make "overwrite" folder always visible

### ISSUE THREAD

**Issue by unqltango** [Modorganizer2/modorganizer#79]
Feature: The "overwrite" "mod" should be always on screen instead of the bottom of the list.

Why: The "overwrite" mod is basically never visible on the screen, as other mods push it out of screen. Still, it is one of the most important folders, since whatever it contains, it is important for the user. It is used when the player uses FNIS, makes a Bashed patch or mods writing their SKSE inis there. 

These are all should be made into new mods and it would be a little easier if the "overwrite" folder would be on the bottom of the mods window all the time (or at least when there is something in it).

**Comment by skwerlman** [comment]
I disagree. A lot of the time, the only thing the overwrite folder contains is SKSE plugin logs, or cache files. These types of files are really unimportant to the user, but constantly wind up in the overwrite folder because of changing file names.

Perhaps a more general 'Pin mod' option would be good to cover your use case without intruding on mine. It'd also be nice if you need to swap between mods frequently for some reason or other.

**Comment by Al12rs** [comment]
I agree with @skwerlman, moving overwrite around will only confuse people. It is on the bottom because it wins all conflicts. It's something that would require some work and not be appreciated by most.

**Comment by Al12rs** [comment]
Closing since no one else seemed to ask for something like this and frankly I don't fell it would be needed.
