### ISSUE TITLE
MO2 Not loading after install

### ISSUE THREAD

**Issue by MattsAttack1** [ModOrganizer2/modorganizer#812]
## The problem:
I can't get MO2 to fully load after I download it and go through the preliminaries. I have disabled virus protection and all firewalls. I have added every folder that I have setup for MO2.exe, mods, modding utilities. As soon as I launch the program (MO2) it just sits there, on my taskbar. When I hover over it, there is just a blank white screen. When I click on the little window from hovering over the taskbar, there is just an outlined transparent window where the opened MO2 interface/home screen should be. I have repeated this process over and over. I even reset my computer. I am running the .exe/installer in admin.

## To Reproduce:

1. Go to 'Mod Organizer 2 (Installer)-6194-2-2-1-1564685587'
2. Click on 'download/open'

## Environment:
* Mod Organizer Version that exhibits the issue: 2.2.1
* Last Mod Organizer Version that did not exhibit the issue (if applicable): NA as I have only used this version, and it has always worked during several clean re-installs because of my inexperience.
* Desktop OS/version used to run Mod Organizer: Windows 10 Home Edition, version 1903

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

## Link to Mod Organizer logs:
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder". You should close MO2 before sending or examining the logs as they are finished writing only after the program is closed.

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by isanae** [comment]
Can you upload `mo_interface.log`?

**Comment by MattsAttack1** [comment]
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/3473179/mo_interface.log)

**Comment by MattsAttack1** [comment]
I got it going. I don't know how.....

**Comment by screamline** [comment]
I am having this exact same problem.

**Comment by Evolution0** [comment]
If you use Avast AV try disabling Cybercapture then run it again.

**Comment by VoHa123** [comment]
Hi,
i'm German, but i hope i can explain my Problem.
It's the same as described. But it happens by me after other circumstances.
I use MO2 ca. 3 Month without any great Problems. All was running fine. Had to learn to config some thing, but was not to heavy.
The only Thing what was nerving me was the Gui what seems to be buggy. I use higher DPI because my Eyes are not the Best and so the GUI is often not really fitting the Screen. Or it jumps out of my
Focus. So i must often klick max. Windowssize.
Yesterday evenning this happens again, and so i clicked my Tab to max the Windows what lead to a better View normaly. But this time absolut wierd thing happens. It minimizes the Program-Window into the Taskbar. Every try to max in the Normal-Gui Windows is not possible. It shows a Blank white Window in the Taskbar, not more, not less. Clicking on it does nothing. In Taskmanager the Process from MO2 is running.
Thing what i've tried are:
-controlling any possible Logs. Nothing wrong, but: ther are no Logs in the MO2 LogFolder. Absolute emptyness.
-next Step was a ReInstall over the existing Version. Nothing happens. Problem is not solved.
-i installed MS Framework again + F4SE and DirectX. No changing...
-so i decided to remove MO2 completly from my PC, means: i took all Registryentrys out and searching fron Dead Files that belongs to MO2 manually. I hoped that will do it.
-New Install: nothing happend. So i'm on a Point that i can not use MO2 (2.2.1) not any longer. 
And that is really frustrating. I like MO2 and the other Modmanagers not so much.

I forgot:
Win 10 64 Bit (1903), no logs, because ther are none to show.

What now? What causes the Problem, and can it removed?

I try to run an older Version, only to see if the Problem exist ther too. Will see...
Thank you, and hope there is an (easy) solution to this.

PS: what must be done to work on German Translation?

**Comment by isanae** [comment]
The window is probably positioned outside your screen. Run MO, then press these keys on your keyboard in order: `Alt+Space`, `M`, followed by either the `Left` or `Right` arrow key.

As for translation, join us on the discord, in the #translations channel.

**Comment by VoHa123** [comment]
Hi,
thank you so much :) It was easy, but on this Idea i will never come alone. It was not how you describe it, but near on it: Alt+M, and then Maximieren (German Therm). And there it was, in all this "beautyful looking". My Day is safed now. Form the Translation i will looking later in the Group.
I think MO2 in German was pretty cool. But is a lot work to do. What you can try (i have done it one time) is: you take the Files from the German Translation from MO1, and copy it into the right Folder under MO2. That germanizes over 50% of MO2 in.

**Comment by Al12rs** [comment]
Closing this for organization purposes, please reopen if the issue persists.
