### ISSUE TITLE
Side-by-side Configuration issue.

### ISSUE THREAD

**Issue by PressingMantis** [ModOrganizer2/modorganizer#823]
Dear you,
I am attempting to run the program after manually downloading it.
I have just recently downloaded the C++ 2013 & 2017-19 version, as well as repaired those two programs due to not having MO2 at the time of download (As instructed in the nexus MO2 instructional video). 
The message windows throws my way is "The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.". Ultimately, its just my goal to fix the issue of applying an exe. through NMM by switching to MO2 (Hopefully!). Now I don't know how to utilize an event log or manage sxstrace.exe tool so I'm looking for guidance from this community, hoping someone has seen this before. My programing skills are at ground zero as im sure, like many & I'm in need of some laymans terms. Feeling that this thread will benefit many if answered diligently!
Thanks for any information you can compile,
PressingMantis.

**Comment by LostDragonist** [comment]
Are you using the installer or the standalone archive?  You might want to try the installer if you're not using it already.

Otherwise... you might post a screenshot of your MO install folder.  This kind of error is usually due to some kind of weird install thing like just grabbing ModOrganizer.exe and none of the other files.

**Comment by Al12rs** [comment]
Closing this for organizational purposes, please reopen if you are still experiencing this problem.
