### ISSUE TITLE
MO2 with Oblivion is slow

### ISSUE THREAD

**Issue by tommyonsn** [ModOrganizer2/modorganizer#929]
in oblivion:
after crash one time.
toooooooo slow every press, including open, press...every operation.
log:------------------
2:27:41 reading save games from d:/my documents/my games/ovblivion/saves
2:28:05 close d:/games/modorganizer/oblivion/profiles/default/plugins.txt
2:28:41 timeout
2:28:41 network error 5
2:28:41 Unable to connect to github.com to check version
log: -------------------
I think network interface is different between oblivion and other? Other games load fast.

**Comment by Al12rs** [comment]
Do you have archive conflicts enabled?

**Comment by tommyonsn** [comment]
> Do you have archive parsing enabled? That can be a cause for massive slowdowns on older games. Regarding the github error that makes little sense, unless your oblivion Mo2 installation is getting blocked by antivirus or something while the others aren't.
> In any case we would need the complete logs. Could you drop by discord so we can have a closer look at what is going on?
> https://discord.gg/6GKR9jZ

The other games are all ok but oblivion, so I think it isn't network problem. 
Where is complete logs? 
I deleted all save files and try again, still load slowly.
I saw log below window and found the situation (long time interval) appeared after [close D:/Game/ModOrganizer/Oblivion/profiles/default/plugins.txt] and before [D:\Games\ModOrganizer\Oblivion\profiles\default\lockedorder.txt saved] or [D:\Games\ModOrganizer\Oblivion\profiles\default\archives.txt saved]
for example:
> 7:22:22 close D:/Games/ModOrganizer/Oblivion/profiles/Default/plugins.txt
>7:24:40 D:\Games\ModOrganizer\Oblivion\profiles\Default\lockedorder.txt saved

**Comment by Al12rs** [comment]
To get the logs follow these instructions:
Upload your log files here. Follow these steps:

1) Go in the Settings, Diagnostics tab, set Log Level to Debug.
2) Restart MO.
3) Recreate your problem.
4) Use the "Open Folders" button to open the logs folder.
5) Close MO.
6) Drop mo_interface.log and the most recent usvfs log here. You might need to compress them.

https://cdn.discordapp.com/attachments/458597400638914563/617049541350260794/openlogs.png

**Comment by tommyonsn** [comment]
I upload logs to google drive.
https://drive.google.com/file/d/1gqJ5FCIaPn4FdjHADTSGqtmkhByrAY5d/view?usp=sharing

**Comment by isanae** [comment]
Can you clarify what the problem is? Is MO itself slow when using it, is Oblivion slow to start when you click Run, does it take time to get to the main menu, does it take time to load a game or does the game itself run slow? As for your logs they don't reveal much because you haven't set the level to Debug.

I also see you have Nahimic installed (also known as Sonic Radar or Sonic Suite), which causes problems with MO by making some windows blanks. You should uninstall it.

MO also doesn't seem to be able to connect to the internet for whatever reason.

**Comment by tommyonsn** [comment]
MO itself slow. MO(other games) can conect to the nexus but mo(oblivion).
After I uninstalled sonic. Mo2 restore and can connect nexus account.
Thanks very much!

**Comment by Silarn** [comment]
As far as internet connectivity issues, I recall that there are some connections that use the native Windows functions to make requests. On older Windows versions, a number of modern TLS protocols are not supported and older SSL protocols are being dropped by many webservers due to security flaws.

If this is the problem, there are steps you will need to take to enable the newer protocols in Windows.

**Comment by SuperSandro2000** [comment]
Or update Windows or just replace those native calls

**Comment by Silarn** [comment]
I checked on one of the calls that are failing and they're using the Qt QNetwork classes which should make use of openssl, but I'm not sure if the actual network requests are still being routed through Windows at some point.

**Comment by Al12rs** [comment]
Don't think much can be used from this issue so I'm closing
