### ISSUE TITLE
MO2 Profile Gone After Changing My Username

### ISSUE THREAD

**Issue by KelvinB1** [ModOrganizer2/modorganizer#944]
Hello all!

Recently, I've requested Staff of Nexus to change my username, and when I subsequently logged into my MO2 application, all my mods for Skyrim SE have gone except my saved files.

[img]https://imgur.com/QuupSMf[/img]

Can someone please kindly assist?

Thank you!

**Comment by LostDragonist** [comment]
It's likely the username thing is unrelated and you've either opened up the wrong instance or your ModOrganizer.ini was corrupted (possibly by anti-virus) and you need to fix it.

The first thing I've noticed is that the screenshot has 2.2.0.  It's possible that you opened an old installation instead of your current one.  Look for other installs on your PC.

The next thing to try is the change game button on the toolbar (the far left icon).  This lets you switch between global instances and a portable instance.  See what you have in there and try selecting some different stuff.

Then there's the ModOrganizer.ini thing where you normally store your mods in a non-standard location.  If that's the case and the INI file corrupted, you'd need to set up the paths to the mods folder again in the MO2 settings.

If that last one turns out to be the case, be sure to look into reasons *why* it may have happened.  Are you using an aggressive anti-virus like Bitdefender or Avast?  It may be the culprit.  You might need to go add exclusions, disable features, or uninstall the thing entirely.  (Before you say "it's never been a problem", consider the fact that a key feature of anti-virus programs is that they constantly update and change their behavior in order to thwart malware.)

**Comment by KelvinB1** [comment]
Heya! Thanks for the response!

I managed to fix it - which I not really sure what is the cause.

I changed the path to the original 'mods' folder.

Now all my mods are visible.

Thanks!
