### ISSUE TITLE
plugins.txt empty

### ISSUE THREAD

**Issue by scamish76** [ModOrganizer2/modorganizer#957]
## The problem:

I keep getting the error (red triangle) "g:/mod-tools/mod organizer 2/step sse/plugin.txt empty".... since I'm using windows, shouldn't the paths use a backslash and not a forward slash... i.e. "g:\mod-tools\mod organizer 2\step sse\plugin.txt" ? I tried to correct this in settings>Paths but the paths revert back to using forward slashes. strangely, in the message box at the bottom of MO2, the paths to "lockedorder.txt" and "modlist.txt" both use backslashes as they should and i get the light-bulb icon (I assume this is good). This is a fresh install of win pro 1909, and a fresh install of steam/Skyrim SE as well. I currently have Steam games installed on my "G" drive. This is the same drive I have the skyrim modding tools folder set up. 

## To Reproduce:

**1. open mo2
2. run loot from mo2
3. sort and close loot
4. see warning in message window**

## Environment:

* Mod Organizer Version that exhibits the issue:  **2.2.1**
* Desktop OS/version used to run Mod Organizer:  **win pro 1909 (10.0.18363)**

## Link to Mod Organizer logs:
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder". You should close MO2 before sending or examining the logs as they are finished writing only after the program is closed.

### USVFS:
https://gist.github.com/scamish76/8df53b3dd3969fb096aeecaec0d0620c

### MO Interface:
https://gist.github.com/scamish76/3edcf3d05132fb40fab3b711fe49e48d

**Comment by LostDragonist** [comment]
Have you gotten around to installing any mods with plugins yet?  This sounds like a pretty innocent error message on a new PC install.  The `plugins.txt` *should* be empty as MO has never had a reason to write to it.

**Comment by scamish76** [comment]
Yes.  I added a few mods recommended on step guide 3.0 and still got the
error. That was what prompted me to refresh my windows install, thinking I
had screwed something up.  But even after the reinstallation, I added
different mods and got the same error. MO2 generated the file right away,
but once I ran loot to sort, the file became blank... Not even the "# this
was generated by MO2" text was printed.  It's got me baffled.  Tomorrow at
some point, I can try using an earlier version of win pro thru VM to see if
that could be the problem

Thank you for the quick response,
Mike

**Comment by Al12rs** [comment]
Are you positive that you actually installed mods *with plugins*? If you install texture mods without plugins Loot will just write an empty plugins.txt file, which then Mo2 will read. Since it was written by loot and not Mo2 it will not have the #this is written by Mo2 line.
If you do have plugins installed and they are not getting added then you should post your logs of running loot:

Upload your log files here. Follow these steps:

1) Go in the Settings, Diagnostics tab, set Log Level to Debug.
2) Restart MO.
3) Recreate your problem.
4) Use the "Open Folders" button to open the logs folder.
5) Close MO.
6) Drop mo_interface.log and the most recent usvfs log here. You might need to compress them.

https://cdn.discordapp.com/attachments/458597400638914563/617049541350260794/openlogs.png

**Comment by scamish76** [comment]
Hey..  so I got this all figured out.  Sorry for not testing this further
before submitting a ticket.  Turns out my Cisco AMP for Endpoint was was
blocking certain functions between the applications and I wansnt getting a
notification... Or so I thought.  The blocked application messages were
sent to my work email account and not my personal email account. Got to
work this morning after two week vaca to find the warnings.  I have since
corrected the issue and everything works as it should.  Thank you for your
assistance.
